### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by windwiny** [ibmdb/ruby-ibmdb#1]
some problem in some test case:
---

test1
---

    #coding: utf-8
    require "active_record"
    require "active_record/connection_adapters/ibm_db_adapter"
    require "logger"

    ActiveRecord::Base.logger = Logger.new(STDERR)
    ActiveRecord::Base.establish_connection(
      adapter: 'ibm_db', username: 'db2admin', password: 'db2admin', database: 'sample')

    ActiveRecord::Base.connection.drop_table 'mytest2s' rescue nil

    ActiveRecord::Base.connection.create_table 'mytest2s' do |t|
      t.string :msg
    end

    class Mytest2 < ActiveRecord::Base
    end

    values=['1234', 'abcd', "\u8f93\u5165"]

    values.each do |vs|
      Mytest2.create(msg: vs)
      v1 = Mytest2.last
      v2 = Mytest2.find_by_sql(["select * from mytest2s where msg like ?", '%'+vs+'%'])
      p [vs, v1.msg == vs, v2.size, v2[0]]
    end

return

    ["1234", true, 1, #<Mytest2 id: 1, msg: "1234">]
    ["abcd", true, 1, #<Mytest2 id: 2, msg: "abcd">]
    ["\u8F93\u5165", true, 0, nil]

line 3, insert and get last row is ok. but find_by_sql return nil

----

test2
---

    #coding: utf-8
    require "ibm_db"

    db=IBM_DB.connect "sample", 'db2admin', 'db2admin'
    IBM_DB.exec db, "drop table test1"
    IBM_DB.exec db, "create table test1 (msg varchar(255) )"

    ['1234', 'abcd', "\u8f93\u5165"].each do |vs|
      IBM_DB.exec db, "insert into test1(msg) values('#{vs}') "
      ts=IBM_DB.exec db, "select * from test1 where msg like '#{vs}' "
      xx=IBM_DB.fetch_array(ts)
      p [xx[0], vs, xx[0]==vs]
    end

    IBM_DB.close db

return

    ["1234", "1234", true]
    ["abcd", "abcd", true]
    ["\u6748\u64B3\u53C6", "\u8F93\u5165", false]

line 3, query data is different to inserted data

----

test3
---

    #coding: utf-8
    require "ibm_db"

    db=IBM_DB.connect "sample", 'db2admin', 'db2admin'
    IBM_DB.exec db, "drop table test1"
    IBM_DB.exec db, "create table test1 (msg varchar(255) )"

    ['1234', '3434', 'abcd', "\u8f93\u5165"].each do |vs|
      st = IBM_DB.prepare db, "insert into test1(msg) values(?) "
      IBM_DB.bind_param st, 1, vs #, IBM_DB::SQL_PARAM_INPUT, IBM_DB::SQL_CHAR
      IBM_DB.execute st

      st = IBM_DB.prepare db, "select * from test1 where msg like ? "
      IBM_DB.bind_param st, 1, vs #, IBM_DB::SQL_PARAM_INPUT, IBM_DB::SQL_CHAR
      IBM_DB.execute st

      xx=IBM_DB.fetch_array(st)
      if xx
        p [xx[0], vs, xx[0]==vs]
      else
        p false
      end 
    end

    IBM_DB.close db

return

    ["1234", "1234", true]
    ["3434", "3434", true]
    eval:1:in `block in <main>': undefined local variable or method `abcd' for main:Object (NameError)
            from 111.rb:11:in `execute'
            from 111.rb:11:in `block in <main>'
            from 111.rb:8:in `each'
            from 111.rb:8:in `<main>'

prepare/bind_param/execute raise error

----
env
---
DB2 v9.7.500.4299
sample codepage is UTF-8
windows xp
ruby 2.0.0p481 (2014-05-08) [i386-mingw32]
ibm_db (2.5.18 x86-mingw32)

**Comment by arvindgu** [comment]
Show issue #34
