### ISSUE TITLE
require 'ibm_db' fails with ruby 2.6.6

### ISSUE THREAD

**Issue by jerren1122** [ibmdb/ruby-ibmdb#101]
**Background:** 
Ruby Version: 2.6.6
IBM_DB Gem Version: (5.0.2 x86-mingw32)
Operating System: Windows 
Error: LoadError (126: The specified module could not be found.   - C:/Ruby26/lib/ruby/gems/2.6.0/gems/ibm_db-5.0.2-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so)

Overview: When requiring ibm_db the above error is returned. I reverted back to ruby 2.3.3 and IBM_DB gem version 3.0.5 and am not experiencing the issue.

**Comment by jerren1122** [comment]
Very similar to bug 94 in this same thread

**Comment by akhilravuri1** [comment]
Hi @jerren1122 

Please set set RUBY_DLL_PATH=path\to\clidriver\bin

Thanks,
Akhil

**Comment by jerren1122** [comment]
Sweet thanks, that was what I was missing, appreciate it.
