### ISSUE TITLE
Failing to install : SQLConnect' undeclared (first use in this function)

### ISSUE THREAD

**Issue by CristianPContreras** [ibmdb/ruby-ibmdb#104]
I am trying to install the latest driver (ibm_db '5.0.2'), and I am getting an error in the logs "'SQLConnect' undeclared (first use in this function)" that is causing the installation to abort.

Environment
=========
OS = MAC Mojave version 10.14.6
Ruby Version :  ruby-2.7.1 

Command
========
gem install ibm_db -v '5.0.2' --source 'http://rubygems.org/'

Console output
============
Building native extensions. This could take a while...
ERROR:  Error installing ibm_db:
        ERROR: Failed to build gem native extension.

    current directory: /Users/crcontreras/.rvm/gems/ruby-2.7.1/gems/ibm_db-5.0.2/ext
/Users/crcontreras/.rvm/rubies/ruby-2.7.1/bin/ruby -I /Users/crcontreras/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0 -r ./siteconf20200715-72518-1wesnud.rb extconf.rb
/Users/crcontreras/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- zip (LoadError)
        from /Users/crcontreras/.rvm/rubies/ruby-2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/crcontreras/.rvm/gems/ruby-2.7.1/extensions/x86_64-darwin-18/2.7.0/ibm_db-5.0.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/crcontreras/.rvm/gems/ruby-2.7.1/gems/ibm_db-5.0.2 for inspection.
Results logged to /Users/crcontreras/.rvm/gems/ruby-2.7.1/extensions/x86_64-darwin-18/2.7.0/ibm_db-5.0.2/gem_make.out

MKMF LOG
=========

gil_release_version is:
/* begin */
1: #ifndef GIL_RELEASE_VERSION
2: #define GIL_RELEASE_VERSION
3: #endif
/* end */

unicode_support_version is:
/* begin */
1: #ifndef UNICODE_SUPPORT_VERSION
2: #define UNICODE_SUPPORT_VERSION
3: #endif
/* end */

have_library: checking for SQLConnect() in -ldb2... -------------------- yes

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/home/rakhil/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/clidriver/lib -Wl,-rpath,/home/rakhil/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm   -lm   -lc"
/home/rakhil/ruby_exe/lib/ruby/2.6.0/mkmf.rb:406: warning: Insecure world writable dir /work/rakhil in PATH, mode 040777
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/home/rakhil/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/clidriver/lib -Wl,-rpath,/home/rakhil/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm   -lc"
conftest.c: In function 't':
conftest.c:14:57: error: 'SQLConnect' undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                         ^~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-cast-function-type'
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return 0;
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/home/rakhil/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/clidriver/lib -Wl,-rpath,/home/rakhil/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return 0;
13: }
14: extern void SQLConnect();
15: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

have_header: checking for gil_release_version... -------------------- yes

"gcc -E -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/home/rakhil/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <gil_release_version>
/* end */

--------------------

have_header: checking for unicode_support_version... -------------------- yes

"gcc -E -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/home/rakhil/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <unicode_support_version>
/* end */

--------------------

**Comment by akhilravuri1** [comment]
Hi @CristianPContreras 

We haven't tested our driver on mac OS and we don't claim support for this.
```
List of Operating Systems tested
--------------------------------
Linux 32/64
Windows 32
AIX 32/64
Remote i5/OS (iSeries)
Remote z/OS (DB2 UDB for zOS)
```
But  I will try to install it on macOS and reproduce the issue.

Please use ruby 2.6.5 and install zip package ``` gem install zip``` before installing ibm_db 'gem install ibm_db'
Thanks,
Akhil

**Comment by CristianPContreras** [comment]
Thank you very much for responding so quickly. I tried the above, and I was able, to successfully install the driver. The problem I am encountering now is that when I try to execute a query my ruby environment crashes. 


#<Thread:0x00007ff1c124b750@/Users/crcontreras/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        3: from /Users/crcontreras/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:300:in `block in run'
        2: from /Users/crcontreras/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:300:in `loop'
        1: from /Users/crcontreras/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `block (2 levels) in run'
/Users/crcontreras/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:301:in `sleep': stack level too deep (SystemStackError)
[BUG] Bus Error at 0x00007ff1c4d9ed70
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.

**Comment by CristianPContreras** [comment]
By any chance, have you had a chance to look at the above issue? I would be grateful for any input you could provide.

**Comment by akhilravuri1** [comment]
Hi @CristianPContreras 

I tried to install the driver in mac but I wasn't successful. I am facing the first issue which you faced(Installation issue).
The only difference is you have used rvm and I am using rbenv.

Thanks,
Akhil

**Comment by CristianPContreras** [comment]
Thank you very much for trying. I guess since mac is not supported I will have to use a different driver instead. 

Again thank you very much for your help.

Cristian
