### ISSUE TITLE
Can't install PDO_IBM driver

### ISSUE THREAD

**Issue by PiotrDevCAN** [ibmdb/ruby-ibmdb#108]
Hi,
For a longer time I have been facing a difficulty in finding working PDO_IBM driver for PHP version 7.3.22 
Initially I tried to install the driver through pecl install pdo_ibm command but it didn't work at all.
Then I tried to compile it on my own through combination of MAKE and INSTALL commands however without any positive result.

![image](https://user-images.githubusercontent.com/65507233/91988792-fd788000-ed2f-11ea-81d2-7bfc8632e68e.png)

Can you give me a hand and guide how can I finish a compilation of the driver ?
Or send me an .SO file which is suitable for a following version of PHP:

PHP 7.3.22 (cli) (built: Sep  1 2020 09:44:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.22, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.22, Copyright (c) 1999-2018, by Zend Technologies

**Comment by akhilravuri1** [comment]
Hi @PiotrDevCAN 

Can you please raise your issue in this page https://github.com/ibmdb/php_ibm_db2/issues

Thanks,
Akhil

**Comment by shilumathai** [comment]
Sorry, the right place to report php ibm driver issue is  below
https://pecl.php.net/package/ibm_db2
https://pecl.php.net/package/pdo_ibm

**Comment by IBMAmarPY** [comment]
Hi @PiotrDevCAN ,
Can you please check the installation instructions here -> https://github.com/php/pecl-database-ibm_db2

Copying the instructions here for your reference:
Prerequisite

CLIDRIVER should be installed in your system. If not installed Download from the below link.
https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/
.
.
if IBM_DB_HOME and LD_LIBRARY_PATH environment variable not set then set them with installed CLIDRIVER.
(say CLIDRIVER installed at "/home/user/clidriver")

export IBM_DB_HOME=/home/user/clidriver 
export LD_LIBRARY_PATH=/home/user/clidriver/lib
export PATH=/home/user/clidriver/bin:$PATH

1) pecl install ibm_db2
        
2) Open the php.ini file in an editor of your choice. Edit the extension entry in the
   php.ini file in the <local_php_directory>/php/lib directory to reference the PHP driver:
       extension=ibm_db2.so
       
3) Ensure that the PHP driver can access the libdb2.so CLI driver file by
   setting the LD_LIBRARY_PATH variable for Linux and UNIX operating systems
   other than the AIX® operating system. For AIX operating system, you must set LIBPATH variable. 

4) Optional: If the PHP application that is connecting to an IBM database server is running ini
   the HTTP server environment, add the LD_LIBRARY_PATH variable in the httpd.conf file.

Thanks!

**Comment by IBMAmarPY** [comment]
From the output you provided, clidriver's sqlcli1.h header file is not found. Please make sure you have the clidriver installed and then follow the steps I mentioned.
