### ISSUE TITLE
Running against DB2 v11 or v12 throws error; 3-year old issue.

### ISSUE THREAD

**Issue by matthewkrom** [ibmdb/ruby-ibmdb#109]
This appears to still be an issue. See Feb 24 comment: Not only does it throw an error against v11, it also throws an error against v12. The latest source code for ibm_db_adapter.rb at line 800 clearly does not handle v11 or 12 (only 08, 09, and 10).  This has been an open issue for 3 years now. Is this library seriously maintained?

_Originally posted by @matthewkrom in https://github.com/ibmdb/ruby-ibmdb/issues/73#issuecomment-703297840_

**Comment by akhilravuri1** [comment]
Hi @matthewkrom 

Sorry for the inconvenience.

I will try to reproduce the bug and fix it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Able to reproduce it and pushed the commit to github..will release this fix with 5.1.0 version.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @matthewkrom 

ibm_db 5.1.0 version is released in which zos 11 and 12 are handled.
Please install the latest driver.

Thanks,
Akhil

**Comment by matthewkrom** [comment]
Will do! Thank you.
