### ISSUE TITLE
Connection to an IBM i database server failed because of a licensing problem

### ISSUE THREAD

**Issue by AdminDev826** [ibmdb/ruby-ibmdb#110]
I have a project which should connect to db2 for IBM I from linux.
When I tried to install ibm_db gem, it failed.
So I downloaded DSClients-linuxx64-dsdriver and set IBM_DB_HOME with:
export IBM_DB_HOME=/home/ubuntu/db2_cli_odbc_driver/clidriver
I was then able install the ibm_db gem successfully.
But when the project tries to connect to the db2 database for IBM I, I'm getting a licensing problem.
I googled this problem and these two links appear to be useful:
https://groups.google.com/forum/#!topic/ibm_db/EmK-CcsioZ0
https://stackoverflow.com/questions/50799800/ibm-db-gem-on-ruby-2-3-4-missing-dependency
However, I'm finding it confusing.
Should I purchase license for connection db2 server for IBM i from Linux?
Or is the odbc driver which I've set to IBM_DB_HOME wrong or the wrong version?
Can you please help resolve this issue?

**Comment by akhilravuri1** [comment]
Hi @AdminDev826 

Yes, you need to purchase a license for IBM Db2(i series) connection.

Thanks,
Akhil

**Comment by bimalkjha** [comment]
@AdminDev826 Connection from ibm_db to Db2 for IBMi from linux is not free. It require db2connect license to be applied either on IBMi server or linux client. Check with your IBM i sysadmin which may have db2connect license that they can activate on server. If IBM I is configured to accept connection from linux client, then you do not need license file. Else, you need to buy db2connect license from IBM of same version as the clidriver pointed by IBM_DB_HOME and copy it under clidriver/license directory.
[This](https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity-and-sql1598n-error) doc has more info about it though it is not for ruby driver, but equally applicable. Thanks.
