### ISSUE TITLE
Win10, RoR 6, DB2 11.5, Data Server Driver Package: am unable to run 'gem install ibm_db'

### ISSUE THREAD

**Issue by dsjm1** [ibmdb/ruby-ibmdb#111]
I am using RoR 6 with MySql and have been for several RoR versions. It is on Windows 10.

I recently needed to switch from MySql to DB2 so have been looking at how
to generate and use the ibm-db gem. I have past experience with DB2.

I have installed IBM Db2 11.5 and Admin-tools and Dev-tools and Data Server Driver package.
Have also installed IBM Data Studio Client as well as the SAMPLE DB. I can access SAMPLE ok.
I also installed Oracle SQL Developer & followed the IBM instructions to point it to DB2.
Oracle SQL Developer also works ok accessing the IBM DB2 SAMPLE database.
I can also run 'db2cli' in a cmd window and it appears to run ok.

Am now ready to try 'gem install ibm_db'

I have added the below 2 windows env variables as per various instructions
RUBY_DLL_PATH=C:\IBMDB2\SQLLIB\clidriver\bin  (it has 2 files, one is IBMLDAPauthclient64.dll)
IBM_DB_HOME=C:\Ruby266-x64\lib\ruby\gems\2.6.0\gems\ibm_db-5.1.0  
(the above folder contains 6 files and only 3 sub-folders:- ext, lib, test. There is no 'include' sub-folder).

I have created a test app called tstdb2-1 and in it's Gemfile I have ...
# Bundle db2
gem 'ibm_db', '~> 5.0.2'

BUT, when I try to run 'gem install ibm_db' I get the following error ...

**********************************************************************
c:\railsapps>gem install ibm_db
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing ibm_db:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby266-x64/lib/ruby/gems/2.6.0/gems/ibm_db-5.1.0/ext
C:/Ruby266-x64/bin/ruby.exe -I C:/Ruby266-x64/lib/ruby/2.6.0 -r ./siteconf20210225-6644-1ddmcq2.rb extconf.rb
extconf.rb:100: warning: already initialized constant ZIP
extconf.rb:46: warning: previous definition of ZIP was here
extconf.rb:103: warning: already initialized constant DOWNLOADLINK
extconf.rb:45: warning: previous definition of DOWNLOADLINK was here
Detected 64-bit Ruby

Detected platform - windows 64
Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the 'gem install ibm_db' command

 C:\Ruby266-x64\lib\ruby\gems\2.6.0\gems\ibm_db-5.1.0/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby266-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/ibm_db-5.1.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby266-x64/lib/ruby/gems/2.6.0/gems/ibm_db-5.1.0 for inspection.
Results logged to C:/Ruby266-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/ibm_db-5.1.0/gem_make.out

c:\railsapps>

**********************************************************************

The below folder 'include' is certainly not present (I noticed the script is using a unix style slash = /include) ??? 
C:\Ruby266-x64\lib\ruby\gems\2.6.0\gems\ibm_db-5.1.0/include folder not found.

Am needing help to resolve this 

Thanks  (see attached output files)

**********************************************************************
ATTACHED #1 gem_make.out
current directory: C:/Ruby266-x64/lib/ruby/gems/2.6.0/gems/ibm_db-5.1.0/ext
C:/Ruby266-x64/bin/ruby.exe -I C:/Ruby266-x64/lib/ruby/2.6.0 -r ./siteconf20210225-6644-1ddmcq2.rb extconf.rb
extconf.rb:100: warning: already initialized constant ZIP
extconf.rb:46: warning: previous definition of ZIP was here
extconf.rb:103: warning: already initialized constant DOWNLOADLINK
extconf.rb:45: warning: previous definition of DOWNLOADLINK was here
Detected 64-bit Ruby
 
Detected platform - windows 64
Detected usage of IBM Data Server Driver package. Ensure you have downloaded 64-bit package of IBM_Data_Server_Driver and retry the 'gem install ibm_db' command
 
 C:\Ruby266-x64\lib\ruby\gems\2.6.0\gems\ibm_db-5.1.0/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly
 

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby266-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/ibm_db-5.1.0/mkmf.log

extconf failed, exit code 1

**********************************************************************

ATTACHED:  mkmf.log
gil_release_version.h is:
/* begin */
1: #ifndef GIL_RELEASE_VERSION_H
2: #define GIL_RELEASE_VERSION_H
3: #endif
/* end */

unicode_support_version.h is:
/* begin */
1: #ifndef UNICODE_SUPPORT_VERSION_H
2: #define UNICODE_SUPPORT_VERSION_H
3: #endif
/* end */

have_library: checking for SQLConnect() in -ldb2... -------------------- yes

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm   -lm   -lc"
/home/rakhil/ruby_exe/lib/ruby/2.6.0/mkmf.rb:406: warning: Insecure world writable dir /work/rakhil in PATH, mode 040777
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm   -lc"
conftest.c: In function 't':
conftest.c:14:57: error: 'SQLConnect' undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                         ^~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-cast-function-type'
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return 0;
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"gcc -o conftest -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable conftest.c  -L. -L/home/rakhil/ruby_exe/lib -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -Wl,-rpath,/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/rakhil/ruby_exe/lib -L/home/rakhil/ruby_exe/lib -lruby-static -lz -lpthread -lrt -lrt -ldl -lcrypt -lm  -ldb2  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return 0;
13: }
14: extern void SQLConnect();
15: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

have_header: checking for gil_release_version.h... -------------------- yes

"gcc -E -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <gil_release_version.h>
/* end */

--------------------

have_header: checking for unicode_support_version.h... -------------------- yes

"gcc -E -I/home/rakhil/ruby_exe/include/ruby-2.6.0/x86_64-linux -I/home/rakhil/ruby_exe/include/ruby-2.6.0/ruby/backward -I/home/rakhil/ruby_exe/include/ruby-2.6.0 -I. -I/work/rakhil/ruby_5.1.0/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/include    -O3 -ggdb3 -Wall -Wextra -Wdeclaration-after-statement -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wrestrict -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <unicode_support_version.h>
/* end */

--------------------

**********************************************************************

**Comment by akhilravuri1** [comment]
Hi @dsjm1 

You have installed ruby 64 bit. But or driver supports ruby 32 bit(ruby 2.6.6 x84) only on windows.

Thanks,
Akhil

**Comment by dsjm1** [comment]
> Hi @dsjm1
> 
> You have installed ruby 64 bit. But or driver supports ruby 32 bit(ruby 2.6.6 x84) only on windows.
> 
> Thanks,
> Akhil

Akhil,

Thanks for replying.

As you know, trying to find current information on ibm_db and the correct drivers is a dauting task. I have spent days just to get to the above.

What I am hoping is that you can offer some help such as where to go to get the 32-driver and perhaps a name of the downloadable file etc:  - I am asking this because again I am spending hours trying to sort out useless links on this topic.

Am hoping you can name the Driver file I need to download and where I can get it (i.e. from IBM Passport Advantage or from IBM fixpack downloads (with a name or link)

Cheers and thanks

Doug M

**Comment by akhilravuri1** [comment]
Hi @dsjm1 

https://rubyinstaller.org/downloads/archives/ from here download the x86 version of ruby and install ibm_db package.
It downloads the clidriver. No need to install the clidriver explicitly.

Thanks,
Akhil
