### ISSUE TITLE
IBM_DB 5.1.0 is not working with Ruby 2.5.5

### ISSUE THREAD

**Issue by aliciasjohnson** [ibmdb/ruby-ibmdb#112]
I'm currently upgrading from Ruby 2.3 to 2.5. Previously i used IBM_DB 3.0.5. with 2.3 no issues. While trying to upgrade to the newer gems with 2.5, and setting up the RUBY_DLL_PATH as instructed, I am still getting the below issue:

irb(main):001:0> require 'ibm_db'
Traceback (most recent call last):
       11: from C:/Ruby25/bin/irb.cmd:19:in `<main>'
       10: from (irb):1
        9: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        8: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        7: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        6: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-5.1.0-x86-mingw32/lib/ibm_db.rb:21:in `<top (required)>'
        5: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        4: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:70:in `require'
        3: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-5.1.0-x86-mingw32/lib/mswin32/ibm_db.rb:93:in `<top (required)>'
        2: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        1: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:122:in `require'
LoadError (126: The specified module could not be found.   - C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-5.1.0-x86-mingw32/lib/mswin32/rb2x/i386/ruby26/ibm_db.so)

I previously saw someone else had this issue, but the ticket was closed with no resolution. 

If someone could help me with this issue, I would appreciate it.

**Comment by akhilravuri1** [comment]
Hi @aliciasjohnson 

I am trying to reproduce the issue. Please give me some time.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @aliciasjohnson 

I am able to reproduce the issue. I will fix this and will let you know when we release the latest version.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @aliciasjohnson 

A new version of the ibm_db(5.2.0) gem is available.
This version has the fix related to ruby 2.5 please install this version and let me know if you face any issues.

Thanks,
Akhil
