### ISSUE TITLE
Sql syntax error connection from rails 6.0.3 to informix 

### ISSUE THREAD

**Issue by bnadav** [ibmdb/ruby-ibmdb#114]
Hi all, I just tried installing ibmdb 5.2.0 and tried run a simple find from consol, but got a sql syntax error. Any ideas ?
It seems to me that this exact syntax is not compatible with informix.
Thanks

irb(main):001:0> MonUser.first
  **MonUser Load (4.8ms)  SELECT mon_users.* FROM mon_users ORDER BY mon_users.id ASC FETCH FIRST 1 ROWS ONLY**
Traceback (most recent call last):
        1: from (irb):1
RuntimeError (Failed to execute statement due to: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201)
irb(main):002:0>

**Comment by akhilravuri1** [comment]
Hi @bnadav 

This issue does not exist with Luw, zos and Iseries servers.
Can you please give a try with  MonUser.first(1)

Thanks,
Akhil

**Comment by bnadav** [comment]
Hi @akhilravuri1 
Thanks for your reply.
I used a docker container of informix developer-database. 
The host is my windows pc. I used ubuntu in wsl2 as host linux.

 MonUser.first(1) resulted in the same error:

nadav@nite-3440:~/rails-projects/myApp$ bundle exec rails c
Loading development environment (Rails 6.0.3)
irb(main):001:0> MonUser.first(1)
  MonUser Load (8.2ms)  SELECT mon_users.* FROM mon_users ORDER BY mon_users.id ASC FETCH FIRST 1 ROWS ONLY
Traceback (most recent call last):
        1: from (irb):1
RuntimeError (Failed to execute statement due to: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201)
irb(main):002:0> exit

**Comment by praveen-db2** [comment]
@bnadav This error is thrown from server. Nothing to do with our adapter or cli driver. If you form correct query it should work. Or you can try using informix specific ruby driver/adapter. Closing this issue as we dont support for Informix. User is free to reopen if he finds any issue specific to DB2.
