### ISSUE TITLE
Is DB2/SUN64 9.1.9 still supported as a remote connection?

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#115]
Hi, could you help me by clarifying a questions?

A client runs DB2 version `9.1.9` on SunOS (`DB2/SUN64 9.1.9`). The client was using `ibm_db` version `2.5.18` in connection with Rails `4.1.2` for a long time. In the process of upgrading to Rails `6.0.3` we also updated the `ibm_db` gem to the latest version (`5.2.0`). My question: Does the latest version of this gem still support remote connections to `DB2/SUN64 9.1.9`? I can connect and run some queries, but I want to be sure that it's officially supported.

**Comment by bimalkjha** [comment]
@jfahrenkrug Db2 V9.1.9 is out of support. Only Db2 V11 onwards is supported as of now. Thanks.

**Comment by bimalkjha** [comment]
@jfahrenkrug Db2 V9.1.9 is out of support. Only Db2 V11 onwards is supported as of now. Thanks.

**Comment by jfahrenkrug** [comment]
@bimalkjha Thank you for your quick reply. Could you tell me which version of this gem is the last version to support 9.1.9?

**Comment by bimalkjha** [comment]
@jfahrenkrug We always refresh clidriver used by gem to the latest level of Db2. So, irrespective of gem version, if someone installs gem without setting IBM_DB_HOME envrionment variable pointing to a preinstalled copy of db2 client or server, gem automatically downloads latest clidriver and use it. i.e. once clidriver get updated, all versions of gem will use the latest db2 driver at client side.
As I understood, you are using DB2 V9.1.9 as remote database server. In that case, you can install `IBM Data Server Driver Package` of version Db2 V11.1 latest fix pack, set env var `IBM_DB_HOME=<full_path_of_db2_client_install_directory>`, then install gem. A client of Db2 V11.1 can connect to Db2 v9.1.9 server. Thanks.

**Comment by jfahrenkrug** [comment]
@bimalkjha Thanks so much for your reply, that's very helpful!
