### ISSUE TITLE
Zip gem not required in Gemspec

### ISSUE THREAD

**Issue by davidahopp** [ibmdb/ruby-ibmdb#116]
I just recently tried installing this gem on a brand new machine and the install of the ibm_db gem was failing on the `require 'zip'` in `extconf.rb:6`. After I manually installed Zip `gem install zip` I was then able to successfully install the ibm_db gem.

**Comment by akhilravuri1** [comment]
Hi @davidahopp 

Thanks for reporting the issue. We will add a zip package to our dependencies list.

Akhil
