### ISSUE TITLE
Using ibm_db without activerecord

### ISSUE THREAD

**Issue by Backbone81** [ibmdb/ruby-ibmdb#118]
I am using ibm_db 5.2.0 with Ruby 3.0.2 and Rails 6.1.4.1 on Ubuntu 20.04. I do not need ibm_db support for activerecord and only use the low level functions in the IBM_DB module for querying data on a DB2 server.

The dependency on 'activerecord', '>= 5.0.7', '<=6.0.3' which was added in https://github.com/ibmdb/ruby-ibmdb/commit/57bb6f67a5035403c62f0a1d359cc0ec5c2452de prevents this usage (btw '<=6.0.3' prevents the usage of 6.0.3.7 which fixed some security issues - '<6.0.4' would probably work better). I worked around this by forking the project and removing that dependency and use a custom built rubygem file.

Is this use case something which is not officially supported? Or was the addition of the activerecord dependency an oversight? I can imagine splitting ibm_db into two rubygems would solve this issue. One rubygem with the low level API and a second rubygem with support for activerecord using the first rubygem and activerecord as dependency. Users could pick and choose, if they need full support for activerecord or not.

**Comment by praveen-db2** [comment]
@Backbone81 this takes lot of efforts from our side, as of now we are working on to support Ruby 3.0 with Rails 6.1 and later Ruby 3.1 with Rails 7.0. We will think about your suggestion once we have enough bandwidth.

**Comment by praveen-db2** [comment]
@Backbone81 we have released newer gem version 5.3.1 in support of ruby 3.0 on rails 6.1. Closing this issue, you are free to open new bug if you find new issues.
