### ISSUE TITLE
IBM_DB 5.2 will not build on new installation of mac Big Sur, Ruby 2.7.2

### ISSUE THREAD

**Issue by carl-t** [ibmdb/ruby-ibmdb#119]
Attempting to `gem install ibm_db` after a clean install of Big Sur, the ibm_db build step fails with 76 warnings and the following 2 errors:

`ibm_db.c:697:12: error: implicit declaration of function 'rb_thread_call_without_gvl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                return rb_thread_call_without_gvl(func, data1, ubf, data2);                        
                                       ^
ibm_db.c:704:4: error: implicit declaration of function 'rb_thread_call_without_gvl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        rb_thread_call_without_gvl(func, data1, ubf, data2);
                        ^
`

The gcc version reports as follows:
`
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
`

Any help much appreciated, many thanks.

**Comment by praveen-db2** [comment]
@carl-t were you able to resolve this issue ?

**Comment by praveen-db2** [comment]
closing this as no response from user.
