### ISSUE TITLE
Cant install ibm_db 4.0.0 gem - Macbook M1

### ISSUE THREAD

**Issue by emgosa** [ibmdb/ruby-ibmdb#120]
ruby 2.5.3

Hello, have been dealing for some hours with this issue and cant resolve it, someone knows how to fix it? What is the reason? Thanks in advance!

**The previous error was fixed by downgrading gemenv to 2.7.5 was a tar_header compiler problem

But at the moment i have a new problem with libdb2.so

`Fetching ibm_db 4.0.0
Installing ibm_db 4.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/joker/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0/ext
/Users/joker/.rbenv/versions/2.5.3/bin/ruby -r ./siteconf20211219-1866-l737et.rb extconf.rb
extconf.rb:93: warning: already initialized constant DOWNLOADLINK
extconf.rb:44: warning: previous definition of DOWNLOADLINK was here
extconf.rb:163: warning: already initialized constant IBM_DB_HOME
extconf.rb:20: warning: previous definition of IBM_DB_HOME was here
extconf.rb:165: warning: already initialized constant IBM_DB_INCLUDE
extconf.rb:150: warning: previous definition of IBM_DB_INCLUDE was here
extconf.rb:166: warning: already initialized constant IBM_DB_LIB
extconf.rb:151: warning: previous definition of IBM_DB_LIB was here
Detected 64-bit Ruby
 
Detected platform - MacOS darwin64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver
creating gil_release_version
creating unicode_support_version
checking for SQLConnect() in -ldb2... no
checking for SQLConnect() in -ldb2... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/joker/.rbenv/versions/2.5.3/bin/$(RUBY_BASE_NAME)
	--with-IBM_DB-dir
	--without-IBM_DB-dir
	--with-IBM_DB-include
	--without-IBM_DB-include=${IBM_DB-dir}/include
	--with-IBM_DB-lib
	--without-IBM_DB-lib=${IBM_DB-dir}/lib
	--with-db2lib
	--without-db2lib
	--with-db2lib
	--without-db2lib
 extconf failure: Unable to locate libdb2.so/a under /Users/joker/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0/ext/../lib/clidriver/lib

Follow the steps below and retry

Step 1: - Install IBM DB2 Universal Database Server/Client

step 2: - Set the environment variable IBM_DB_HOME as below
        
             (assuming bash shell)
        
             export IBM_DB_HOME=<DB2/IBM_Data_Server_Driver installation directory> #(Eg: export IBM_DB_HOME=/opt/ibm/db2/v10)

step 3: - Retry gem install
        

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/joker/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/extensions/-darwin-21/2.5.0/ibm_db-4.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/joker/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0 for inspection.
Results logged to /Users/joker/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/extensions/-darwin-21/2.5.0/ibm_db-4.0.0/gem_make.out

An error occurred while installing ibm_db (4.0.0), and Bundler cannot continue.
Make sure that `gem install ibm_db -v '4.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  ibm_db

Process finished with exit code 5
`

**Comment by emgosa** [comment]
i tried downloading mac64 drivers from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ and sourcing IBM_DB_HOME to the path with no luck

**Comment by emgosa** [comment]
more info about the crash
`gil_release_version is:
/* begin */
1: #ifndef GIL_RELEASE_VERSION
2: #define GIL_RELEASE_VERSION
3: #endif
/* end */

unicode_support_version is:
/* begin */
1: #ifndef UNICODE_SUPPORT_VERSION
2: #define UNICODE_SUPPORT_VERSION
3: #endif
/* end */

have_library: checking for SQLConnect() in -ldb2... -------------------- no

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
conftest.c:13:57: error: use of undeclared identifier 'SQLConnect'
int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
ld: warning: ignoring file /Users/joker/.ibm_driver/clidriver/lib/libdb2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_SQLConnect", referenced from:
      _t in conftest-4baf41.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void SQLConnect();
14: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

find_library: checking for SQLConnect() in -ldb2... -------------------- no

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
conftest.c:13:57: error: use of undeclared identifier 'SQLConnect'
int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
ld: warning: ignoring file /Users/joker/.ibm_driver/clidriver/lib/libdb2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_SQLConnect", referenced from:
      _t in conftest-bb1235.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void SQLConnect();
14: int t(void) { SQLConnect(); return 0; }
/* end */

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
conftest.c:13:57: error: use of undeclared identifier 'SQLConnect'
int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
                                                        ^
1 error generated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: int t(void) { void ((*volatile p)()); p = (void ((*)()))SQLConnect; return !p; }
/* end */

"clang -o conftest -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/-darwin21 -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0/ruby/backward -I/Users/joker/.rbenv/versions/2.5.3/include/ruby-2.5.0 -I. -I/Users/joker/.ibm_driver/clidriver/include -I/Users/joker/.rbenv/versions/2.5.3/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -Wno-error=implicit-function-declaration -fno-common -pipe conftest.c  -L. -L/Users/joker/.rbenv/versions/2.5.3/lib -L/Users/joker/.ibm_driver/clidriver/lib -L. -L/Users/joker/.rbenv/versions/2.5.3/lib  -fstack-protector     -lruby.2.5.3 -ldb2  -lpthread -ldl -lobjc "
ld: warning: ignoring file /Users/joker/.ibm_driver/clidriver/lib/libdb2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_SQLConnect", referenced from:
      _t in conftest-dc2dbe.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     printf("%p", &t);
 9:   }
10: 
11:   return 0;
12: }
13: extern void SQLConnect();
14: int t(void) { SQLConnect(); return 0; }
/* end */

--------------------

`

**Comment by jfahrenkrug** [comment]
@emgosa Hi, do you mind sharing how (or if) you found a solution? The issue was closed on Dec 20, 2021, but there are no details about how it was addressed. Does this gem now have ARM64 (Apple Silicon) support? /cc @praveen-db2

**Comment by bimalkjha** [comment]
@jfahrenkrug IBM do not have any arm64 version of db2 client. So, you need to install x64 version of ruby on M1 Chip system, then it can work. Thanks.
