### ISSUE TITLE
Compilation errors and warnings on recent GCC versions (10.2+)

### ISSUE THREAD

**Issue by zinal** [ibmdb/ruby-ibmdb#124]
There are multiple issues which prevent the driver to be built on modern systems without modifications, and issue a lot of warnings:
1. rb_warn() should not get external data as a format string - that is unsafe, and is detected as errors by recent versions of GCC.
2. STRCASECMP is currently defined in ruby.h, no need to re-define it - so added a check whether it has already been defined
3. Ruby includes <ruby/thread.h> since versions 2.5.x, so the conditional inclusion is not needed. Configuration logic does not set RUBY_THREAD_H anyway.
4. Pre-compiler logic in ibm_Ruby_Thread_Call() is unneeded, because the signature of modern rb_thread_call_without_gvl() does not depend on the platform, and is the same for all Ruby versions 2.5+. The option chosen on Linux causes a compilation warning. Some options look simply incorrect (missing return statement).
5. Some type conversions are needed to avoid the compiler warnings.

**Comment by praveen-db2** [comment]
@zinal closing this as we merged related PR.
