### ISSUE TITLE
Remove UNICODE_SUPPORT_VERSION_H conditional compilation

### ISSUE THREAD

**Issue by zinal** [ibmdb/ruby-ibmdb#126]
It seems that UNICODE_SUPPORT_VERSION_H is always defined for the current version of Ruby Adapter for Db2.
I believe that this variable and all the conditional logic which depends on it should be removed.
That will allow to simplify the driver maintenance and further development.

I can do that myself, but the amount of changes will be significant.
I would like someone having more knowledge about the Adapter to comment on that.

**Comment by praveen-db2** [comment]
@zinal UNICODE_SUPPORT_VERSION_H  was introduced to handle unicode data. Thanks for your suggestion we will check what can be done in future to simplify as much possible.
