### ISSUE TITLE
Rails 6.1 support?

### ISSUE THREAD

**Issue by matthewkrom** [ibmdb/ruby-ibmdb#127]
ibm_db gem 5.2.0 requires activerecord >= 5.0.7 and <= 6.0.3

Rails 6.1 was released in Dec 2020 (14 months ago), and Rails 7.0 is available now.

Will this gem be supported for 6.1?

**Comment by matthewkrom** [comment]
Some extra notes:
 - we'll also be using Ruby 3.1.x
 - we're actually not requiring the ActiveRecord portions; a simple native connection that allows SQL selects would suffice. But, the full ActiveRecord integration in ibm_db is what we've used to date. Thank you.

**Comment by praveen-db2** [comment]
@matthewkrom we are planning to work on Ruby 3.1.x and Rails 7.0, is it ok for you or you need support for Rails 6.1 with Ruby 3.0.

**Comment by matthewkrom** [comment]
Thanks — Rails 7.0 may work well for us; we'll do some testing. It looks like Rails 6.1-to-7.0 ActiveRecord changes were mostly removing deprecated items? I wonder if your Rails 7.0 implementation would also pass Rails 6.1 tests without many changes?

**Comment by praveen-db2** [comment]
@matthewkrom I am planning to skip running on Rails 6.1 and run on Rails 7.0, so I hope it should cover anything left from 6.1 as well.

**Comment by matthewkrom** [comment]
@praveen-db2 Great! When you release the gem, please remember to declare its dependency to accept activerecord 6.1 for example.  The current ibm_db 5.2.0 gem may work well on activerecord 6.1, but we can't try it because the gem declares that it must have activerecord 6.0.3 or lower, correct?

e.g.:   In Gemfile:
    ibm_db (= 5.2.0) was resolved to 5.2.0, which depends on
      activerecord (<= 6.0.3, >= 5.0.7)

**Comment by praveen-db2** [comment]
@matthewkrom sure will note it

**Comment by matthewkrom** [comment]
Hello! Our system update to Rails 6.1 is imminent (ideally) — this ibm_db gem is a major factor for us. Is there something we could do to contribute, or see about testing Rails 6.1 with Ruby 3.0? Not having worked with the source code before (except to allow higher z/OS versions), we'd rather not do that if you're close to having tests running in Rails 6.1. Thank you!

**Comment by matthewkrom** [comment]
I reviewed the ActiveRecord 6.1 release notes https://guides.rubyonrails.org/6_1_release_notes.html#active-record — it doesn't appear ActiveRecord has removed any deprecated methods that are used, EXCEPT for #update_attributes (now #update), which is *only* used in the test suite it appears.

So, could the gemspec be changed to allow up to 6.1.x, and the specs re-run to be checked?

**Comment by praveen-db2** [comment]
@matthewkrom Initially I thought to support ibm_db for Rails 7.0 on Ruby 3.1 but there is lot of issues to be addressed to do so. Hence I am planning to release ibm_db to support Rails 6.1 on Ruby 3.0. Once I complete my tests run will be releasing upgraded version. Later I will start to work on Rails 7.0 on Ruby 3.1. 

Your contributions are always welcome. If you find any changes to be implemented in ibm_db w.r.t Rails 6.1 on Ruby 3.0 you can raise a pull request for the same I ill try merging it or include those changes in my commit.

**Comment by jfahrenkrug** [comment]
@praveen-db2 @matthewkrom Any update on this?

**Comment by praveen-db2** [comment]
@jfahrenkrug Work is going on in full time, it takes some more time (atleast another 2 months). As we have left with many active record test suites to address.

**Comment by matthewkrom** [comment]
Yes @praveen-db2 thank you. Let us know if you need additional "corporate" support, business case, letters of appreciation to support you and your team's efforts.

I wanted to say that for my system, I'm factoring the IBM DB connections into a separate Ruby microservice for now, so that other parts of the app can advance to a newer version of Rails while the IBM DB connection (which is not the primary connection for the app) can stay with Rails 5.2.  Then, once newer Rails support is ready, we'll upgrade the microservice separately.

**Comment by praveen-db2** [comment]
@matthewkrom I am addressing every test suite given by active record. I think this should suffice all your business cases. Since its not supported from long time I see lot of updates needed in IBM_db adapter. I can say now its shaping well. I am only engineer working on this, team is busy in other priorities, definitely your appreciation is very much needed. I ill let you know once I release, you can send an official appreciation letter.

**Comment by jfahrenkrug** [comment]
@praveen-db2 That's fantastic news, thanks so much!!
