### ISSUE TITLE
Rails connecting to IDS - Not recognising Table

### ISSUE THREAD

**Issue by stianh26** [ibmdb/ruby-ibmdb#13]
I am trying to build a Rails(4.0.12, same issue in 4.1.8) application to connect to an existing IDS database (12.10.FC1X4).
Columns in table:
![table](https://cloud.githubusercontent.com/assets/8969145/5466036/d44db516-85dd-11e4-9c08-3b5ade732899.PNG)
Model:
![model](https://cloud.githubusercontent.com/assets/8969145/5466062/30f46b02-85de-11e4-828f-81896f8dc30a.png)
Output:
![outputpo](https://cloud.githubusercontent.com/assets/8969145/5466098/e202ae86-85de-11e4-92bf-7302457d6370.png)
I am expecting to get the entire row back from the DB
Running SQL Directly:
![sql-results](https://cloud.githubusercontent.com/assets/8969145/5466177/67549544-85e0-11e4-8efe-8948e581b656.png)

If I query for non-existing records I do get errors as expected.

Does anyone know what I am doing wrong?
I believe the issue is that the SERIAL8 datatype is not being mapped to a ruby data type (integer I would assume).

Any assistance would be greatly appreciated

Kind Regards,

Stian Henriksen

**Comment by stianh26** [comment]
Hi Praveen,
Thanks for your response - and apologies for my late response.

I have added serial8 to ibm_db_adapter as suggested but still have exactly the same issues as before.

![serial8](https://cloud.githubusercontent.com/assets/8969145/5698173/371903e4-9a42-11e4-9950-775d6ff69773.png)

Do you have any other suggestions?

Cheers,

Stian

**Comment by stianh26** [comment]
Hi Praveen,

I am still nto having any luck with this.

I tried to upgrade to Rails 4.2 and apply your patch from Issue# 16 - but this gives me another error.
![rails4 2](https://cloud.githubusercontent.com/assets/8969145/5934001/b08d82c2-a703-11e4-94f0-09e30e6148f8.png)

Any advice would be greatly appreciated.

Cheers,

Stian

**Comment by mariobriggs** [comment]
in narrowing down the issue, i would go back to 4.0..12 and try without the 'serial8' column  there

**Comment by stianh26** [comment]
Thanks for the quick response

Reverted back to 4.0.12 ­ original issue is back.

I am unable to remove the Serial8 column, as I am connecting to an existing
DB.
I am trying to make a Rails app give external access to an ERP running on
Informix (on linux) to enable users to approve Purchase Orders etc. so I am
unable to change the table structure.


From:  mariobriggs <notifications@github.com>
Reply-To:  ibmdb/ruby-ibmdb
<reply+0088dbb915fa8c7aabd8432a5508597552f13e7c6a6f15dc92cf0000000110e057a39
2a169ce031c799b@reply.github.com>
Date:  Wednesday, 28 January 2015 3:54 PM
To:  ibmdb/ruby-ibmdb <ruby-ibmdb@noreply.github.com>
Cc:  Stian Henriksen <stianh26@gmail.com>
Subject:  Re: [ruby-ibmdb] Rails connecting to IDS - Not recognising Table
(#13)


in narrowing down the issue, i would go back to 4.0..12 and try without the
'serial8' column  there

‹
Reply to this email directly or view it on GitHub
<https://github.com/ibmdb/ruby-ibmdb/issues/13#issuecomment-71794191> .

**Comment by mariobriggs** [comment]
in that case i meant, create a dummy table minus the serial8 column. insert some data and then give it a try

**Comment by stianh26** [comment]
Thanks @mariobriggs 

I have created a new DB on IDS and created two tables, which is populated from the ERP database.

More success indeed (even with the serial8 column)- Record is being returned when ask for a defined number of records.

I get a syntax error when I try to list all records - wither via console "PoTest.all" or via my scaffolded view. The SQL generated is:
SELECT FIRST purchase_order_full.* FROM purchase_order_full 

Problem appears to be the FIRST, does not work without a number (i.e. FIRST 1 or FIRST 10, which works fine) - What can I do to correct the SQL syntax generated?

Still have the issue when connection to the ERP systems database - but I assume that is due to the DB config rather than a connector issue.

**Comment by ibmdb** [comment]
Hi @stianh26 

Could you share what Model method are you invoking? You will have to specify the limit appropriately...

Model.limit(5)

Thanks

Praveen

**Comment by stianh26** [comment]
Hi @praveen,

It happens when using Model.all ­ so not a method I have written myself.
Same error when found model.count for instance.

This appears to be because the SELECT SQL generated by both of these
scenarios are SELECT FIRST, as opposed to SELECT.

Cheers,


From:  ibmdb <notifications@github.com>
Reply-To:  ibmdb/ruby-ibmdb
<reply+0088dbb975ab45f2c640816ac33460fadbee37e3416b65b992cf0000000110e1bcc49
2a169ce031c799b@reply.github.com>
Date:  Thursday, 29 January 2015 5:17 PM
To:  ibmdb/ruby-ibmdb <ruby-ibmdb@noreply.github.com>
Cc:  Stian Henriksen <stianh26@gmail.com>
Subject:  Re: [ruby-ibmdb] Rails connecting to IDS - Not recognising Table
(#13)


Hi @stianh26 <https://github.com/stianh26>

Could you share what Model method are you invoking? You will have to specify
the limit appropriately...

Model.limit(5)

Thanks

Praveen

‹
Reply to this email directly or view it on GitHub
<https://github.com/ibmdb/ruby-ibmdb/issues/13#issuecomment-71992647> .

**Comment by stianh26** [comment]
Hi @praveend / @mariobriggs,

I have found cause of the original issue.

The connector does not return the data for tables where the DB user (form database.yml) in NOT the owner of the table, even thought the user have DBA access to the DB, and All access to the table.

This only happens when I am accessing it through the model though.

When using the IRB console as below - the data is returned. The same user can also query the DB via JDBC or OAT using SQL.
![ibm_db-irb](https://cloud.githubusercontent.com/assets/8969145/5994872/031512c6-aabf-11e4-8178-ae012183ce87.png)

Should the table owner matter?

I cannot use the table owner to connect as this is the ERP superuser.

Suggestions/advice?

Cheers,

Stian

**Comment by ibmdb** [comment]
Hi @stianh26 

Invoking from the model should not really matter here because internally the IBM_DB Adapter is making a similar call as you have in the irb session.

As mentioned earlier possible the serial8 data type is not being recognized. Could you put a default clause [else] in the case statement and see if that part of the code is being hit or might be even try putting the serial8 statement in a separate when condition and give a try?

when /serial8/i
    :integer

Thanks

Praveen

**Comment by stianh26** [comment]
Hi @praveend,
I have added the Serial8 in a separate condition and it is being picked up - it's actually being defined as a integer even if I remove this line all together. - So I am unable to identify what part of the code is being hit.

I have created my own table - which is a identical copy of the table I am tying to hit in the ERP, the only difference is that user 'stianh' is the owner of the table.
This returns data fine.
![po_testok](https://cloud.githubusercontent.com/assets/8969145/6012522/f9654014-ab83-11e4-80be-6727080c13f1.png)
The rowid is converted to integer correctly
![potestclass](https://cloud.githubusercontent.com/assets/8969145/6012533/2ad8a01e-ab84-11e4-8ad5-d5c04d04367c.png)
Changing the credentials in database.yml to another user (with DBA access to database - table has public access)
![potestinformix](https://cloud.githubusercontent.com/assets/8969145/6012557/89fdc7fe-ab84-11e4-9896-408f44468fde.png)

Cheers,

Stian

**Comment by ibmdb** [comment]
Cool! so your issue is resolved?

I will transfer this info to my team so that the next release when made will have this when condition separately.

Thanks

Praveen

**Comment by stianh26** [comment]
My issue is still there - it's just not caused by the serial8 data-type as I first thought.

I only get the data for the model, if the DB user is the table owner (first screen shot above). I can't use the table owner as this is the ERP-super user.

When I create a new user for my web application and give this user access to the DB I only get the #<model>, not the data from the model. And it tells me the table does not exists when I run model.first.class

Cheers,

Stian

**Comment by ibmdb** [comment]
OK no probs. Could you help getting CLI trace [ http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.admin.trb.doc/doc/t0060829.html ] for runs as owner and new user...might be we will get some info from the traces on what could be happening.

As said, if from irb it is working then it should really not matter how you are invoking because internally adapter uses the IBM_DB driver.

Thanks

Praveen

**Comment by stianh26** [comment]
Hi Praveen,

Dump files from trace attached.

Let me know what else I can do to assist.

Cheers,

Stian

From:  ibmdb <notifications@github.com>
Reply-To:  ibmdb/ruby-ibmdb
<reply+0088dbb97867e1db8ad2f16d97dcc127e5939e3d378630fe92cf0000000110e7f3279
2a169ce031c799b@reply.github.com>
Date:  Tuesday, 3 February 2015 10:23 AM
To:  ibmdb/ruby-ibmdb <ruby-ibmdb@noreply.github.com>
Cc:  Stian Henriksen <stianh26@gmail.com>
Subject:  Re: [ruby-ibmdb] Rails connecting to IDS - Not recognising Table
(#13)


OK no probs. Could you help getting CLI trace [
http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.
admin.trb.doc/doc/t0060829.html ] for runs as owner and new user...might be
we will get some info from the traces on what could be happening.

As said, if from irb it is working then it should really not matter how you
are invoking because internally adapter uses the IBM_DB driver.

Thanks

Praveen

‹
Reply to this email directly or view it on GitHub
<https://github.com/ibmdb/ruby-ibmdb/issues/13#issuecomment-72580750> .

**Comment by ibmdb** [comment]
Hi @stianh26 

looks like you replied to the mail with attachment. Github doesn't allow attachments...could you share it on gist or via a zip to praveendrl@in.ibm.com

Thanks

Praveen

**Comment by stianh26** [comment]
Hi @praveend,
So I did the "db2trc fmt tOwner.dmp tOwner.txt" to prepare the gist - but the file is empty?
I am running db2trc installed with the ibm_data_server_driver_package.v.10.5.

What am I doing wrong?
I ran it on both the db host and the rails hosts with the same result.

Is there another tool specific to informix?

Cheers,

Stian

**Comment by stianh26** [comment]
Thank you all for all you assistance.

It turns out when using Informix you need to define the table owner as the schema: in database.yml

So thanks again, all assistance and advice have been greatly appreciated.
