### ISSUE TITLE
Is it possible to set the QUERY OPTIMIZATION in database.yml?

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#131]
It's possible to run a raw SQL command to set the query optimization level, for example: `ActiveRecord::Base.connection.execute("SET CURRENT QUERY OPTIMIZATION 1")`

If we always want to use the same level for all queries, is it possible to set this value once in `database.yml`?

**Comment by praveen-db2** [comment]
@jfahrenkrug yes you can execute any sql query directly using `ActiveRecord::Base.connection.execute(sql)` 

I dont prefer to add in database.yml, each user has different requirement, its better they incorporate it in their application rather adapter implement it.

**Comment by jfahrenkrug** [comment]
@praveen-db2 Thank you, makes sense!
