### ISSUE TITLE
Version 5.3.1 uses "LIMIT 1" instead of "FETCH FIRST 1 ROWS ONLY" causing syntax error

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#136]
After upgrading to version 5.3.1, I'm getting SQL syntax errors because `limit` Active Record statements are now turned into `LIMIT 1` SQL statements, which our DB2 client/server can't handle:

In version 5.2.0, this SQL was successfully executed:
```
SELECT country_codes.* FROM country_codes WHERE country_codes.code = '31' FETCH FIRST 1 ROWS ONLY
```

In version 5.3.1, this SQL is executed:
```
SELECT country_codes.* FROM country_codes WHERE country_codes.code = '31' LIMIT 1
```

That causes this error:
> [IBM][CLI Driver][DB2/SUN64] SQL0104N  An unexpected token "LIMIT" was found following "ry_codes.code = ?".  Expected tokens may include:  "SELECTIVITY".  SQLSTATE=42601 SQLCODE=-104 (ActiveRecord::StatementInvalid)

I'm on Rails version 6.1.0. 

Is there a way to configure the connection to use the `FETCH FIRST ROWS ONLY` syntax instead of the `LIMIT` syntax? This is a blocker for us.

**Comment by praveen-db2** [comment]
@jfahrenkrug will fix this and let you know.

**Comment by jfahrenkrug** [comment]
@praveen-db2 Thank you, I appreciate it :)

**Comment by praveen-db2** [comment]
@jfahrenkrug released v5.3.2 , can you chech and close this issue.

**Comment by praveen-db2** [comment]
@jfahrenkrug can we close this if recent release fixed your issue.

**Comment by jfahrenkrug** [comment]
@praveen-db2 I can confirm this is fixed, thanks!!
