### ISSUE TITLE
5.4.0 Broken release on rubygems.org

### ISSUE THREAD

**Issue by janhoffmann** [ibmdb/ruby-ibmdb#149]
hi @praveen-db2 ,

i think the last release 5.4.0 (yesterday) is not recognized by rubygems.

I saw that for this version 2 releases where published with the same version number (5.4.0)
![image](https://user-images.githubusercontent.com/1494946/228574445-114fca19-d28c-4f43-80f3-a17b2437b7f5.png)

The last release dates to yesterday.

When I download the gem the code does not include the March 20th changes.
![image](https://user-images.githubusercontent.com/1494946/228574976-c9b58c2c-6be9-44fc-8c50-48ccf4fd5de4.png)

![image](https://user-images.githubusercontent.com/1494946/228575279-199a9a70-6319-4ada-8351-91ef7c0a7ed8.png)

Is it possible to increase the version number and re-release the changes. My customers pipelines are stuck due to this error, because ibm seems to have shut of http access (see #146 ).

**Comment by janhoffmann** [comment]
@praveen-db2 Thanks for your effort!

On my local system the fix from @hajee works fine.

**Comment by praveen-db2** [comment]
@janhoffmann Its very intermittent. So I dont want to take chance.

**Comment by praveen-db2** [comment]
@janhoffmann new gem v 5.4.1 released please use, it has @hajee fixes. And you can close this ticket if rest all is fine.
