### ISSUE TITLE
Rails 4.2 - TypeError: superclass mismatch for class ToSql

### ISSUE THREAD

**Issue by mcmorgan** [ibmdb/ruby-ibmdb#15]
When executing `rake db:migrate` the following error is received on a Rails 4.2.0 app running Ruby 2.1.5:

> TypeError: superclass mismatch for class ToSql
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.18/lib/active_record/connection_adapters/ibm_db_adapter.rb:2975:in `<module:Visitors>'

After investigation, I see where the base class of `ToSql` was changed from `Arel::Visitors::Visitor` to `Arel::Visitors::Reduce` via commit https://github.com/rails/arel/commit/a6a7c75ff486657909e20e2f48764136caa5e87e#diff-a044319ea18758df55167af00a0250d9R17.

I have changed the base class of `ToSql` to `Arel::Visitors::Reduce` in this gem, however that leads to another issue:

> ArgumentError: wrong number of arguments (1 for 2)
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:6:in `accept'
/home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.18/lib/active_record/connection_adapters/ibm_db_adapter.rb:731:in `to_sql'

This is happening for a deeper reason that what I have explored so far...

**Comment by praveend** [comment]
Hi @mcmorgan 

Not just changes in Arel there are some changes in Activerecord too that is impacting here. Hence just changing the super class will not help.

I have made the necessary changes in the ibm_db_adapter to be on sync with the new changes and the same is available here https://gist.github.com/praveend/c77a61c028cb47b59326

Give it a try and let me know how it goes 

This patched adapter is compatible only with Rails 4.2 (i.e no backward compatibility). The changes seem to be of significant impact and I will need to spend some time to figure out the best approach to make it backward compatible. Also I have not rigorously tested these changes, hence if you find any problems kindly bare with it and report them so that I can provide the necessary fix.


Wish you a happy new year!!

Thanks

Praveen

**Comment by mcmorgan** [comment]
Thank you so much @praveend. This works for me. I have just a basic app to test it out with at this point, but it looks good.

**Comment by mcmorgan** [comment]
@praveend perhaps if there isn't a way to maintain backward compatibility without bad hacks, a version 3.0.0 could be released which only supports Rails 4.2 +

**Comment by nPn-** [comment]
@praveend   Are there any plans to release the code in your gist in to production?  I have been running on my development machine with a side copy of the code in the gist for a couple of weeks now.  I would like to start testing on Bluemix (switching an existing app from postgres -> db2) and it would be nice to not have to point to a cloned repo.

**Comment by arvindgu** [comment]
@nPn We will be releasing soon the code in production.

**Comment by zambon** [comment]
@arvindgu would you have an ETA?

**Comment by dennisbaskin** [comment]
:+1: on the ETA. I am seeing similar issue just trying to upgrade to Rails 4.0 with Ruby 2.1.1

**Comment by zambon** [comment]
ping! :smile:

**Comment by arvindgu** [comment]
Today we have released new version of ibm_db gem that has support for both Rails 4.2 and Ruby 2.2.  The new version of ibm_db gem is 2.5.25.

**Comment by zambon** [comment]
Awesome news! Thanks @arvindgu!

**Comment by mayuresh-srivastava** [comment]
> When executing `rake db:migrate` the following error is received on a Rails 4.2.0 app running Ruby 2.1.5:
> 
> > TypeError: superclass mismatch for class ToSql
> > /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.18/lib/active_record/connection_adapters/ibm_db_adapter.rb:2975:in `module:Visitors'
> 
> After investigation, I see where the base class of `ToSql` was changed from `Arel::Visitors::Visitor` to `Arel::Visitors::Reduce` via commit [rails/arel@a6a7c75#diff-a044319ea18758df55167af00a0250d9R17](https://github.com/rails/arel/commit/a6a7c75ff486657909e20e2f48764136caa5e87e#diff-a044319ea18758df55167af00a0250d9R17).
> 
> I have changed the base class of `ToSql` to `Arel::Visitors::Reduce` in this gem, however that leads to another issue:
> 
> > ArgumentError: wrong number of arguments (1 for 2)
> > /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/arel-6.0.0/lib/arel/visitors/reduce.rb:6:in `accept' /home/vagrant/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ibm_db-2.5.18/lib/active_record/connection_adapters/ibm_db_adapter.rb:731:in`to_sql'
> 
> This is happening for a deeper reason that what I have explored so far...

Changing to `Arel::Visitors::Reduce ` fixed the issue in my case
