### ISSUE TITLE
Must change to use RubyZip instead of 13 year old Zip Gem!

### ISSUE THREAD

**Issue by sae249833** [ibmdb/ruby-ibmdb#153]
Starting in version 5.3.1, the zip gem, a gem that hasn't been maintained since May 26, 2010, became a dependency. In doing so, and since zip shares the identical module "Zip" with the rubyzip gem, this change will cause bugs with any application that also has a dependency on rubyzip, either directly or through a third-party gem (for example "selenium_webdriver" or "caxlsx").

The zip gem should have never been made a dependency of ibmdb. Please either drop the dependency or switch it to rubyzip.

This should be a high priority issue as it prevents applications with a rubyzip dependencies from upgrading to Rails 7 because all versions of ibmdb compatible with Rails 7 contain the zip gem dependency.

**Comment by praveen-db2** [comment]
@sae249833 Hi thanks for letting us know complications. We will work on it shortly and let you know.

**Comment by praveen-db2** [comment]
Closing this issue as its fixed now. Will be releasing newer version shortly.
