### ISSUE TITLE
Version 5.4.1 requires Rails 7, but gemspec allows for lower versions

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#155]
Version 5.4.1 uses features that were introduced in Rails 7, like `transform_query`: https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L775 (See https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#LL1486C15-L1486C24)

However, the gemspec allows me to install 5.4.1 in my Rails 6 app:
https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/IBM_DB.gemspec#L23

When starting my app, it prints this error:
`NoMethodError (undefined method `transform_query' for #<ActiveRecord::ConnectionAdapters::IBM_DBAdapter:0x0000004018bbacd0>)`

The gemspec should reflect that this version requires Rails 7 or higher.

**Comment by praveen-db2** [comment]
@jfahrenkrug Thanks for pointing, will take care in next release.

**Comment by jfahrenkrug** [comment]
@praveen-db2 Great, thank you!

**Comment by praveen-db2** [comment]
Fixed this issue, will be releasing newer version shortly
