### ISSUE TITLE
DB2 "OFFSET" keyword is incompatible with DB2 Servers < 11

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#156]
Hello @praveen-db2,

My client is using DB2 Version 9. We depend on the ruby_ibm gem. I've noticed that recent versions generate invalid SQL queries for DB2 9 when the Rails "offset" method is used:

```
irb(main):002:0> DialogEntry.offset(5).limit(3)
D, [2023-06-29T09:39:53.576168 #9] DEBUG -- :   DialogEntry Load (1.5ms)  SELECT dialog_entries.* FROM dialog_entries /* loading for inspect */ OFFSET 5 ROWS FETCH FIRST 3 ROWS ONLY
Traceback (most recent call last):
ActiveRecord::StatementInvalid (ActiveRecord::StatementInvalid: [IBM][CLI Driver][DB2/SUN64] SQL0104N  An unexpected token "5 ROWS" was found following "or inspect */ OFFSET".  Expected tokens may include:  "<space>".  SQLSTATE=42601 SQLCODE=-104)
```

I think this is where it's added: https://github.com/ibmdb/ruby-ibmdb/blob/cb63ebe8018b079924cf40a180cd59a53f887265/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L3767

Is it possible to solve this somehow? I'm using Rails 7.0.5 and version 5.4.1 of the ibmdb gem.

Thank you!

**Comment by praveen-db2** [comment]
@jfahrenkrug we do not support for DB2 version 9. Request to upgrade to 11.x versions

**Comment by jfahrenkrug** [comment]
@praveen-db2 Thank you, understood.
