### ISSUE TITLE
Invalid OFFSET / FETCH FIRST ROWS ONLY queries are being generated

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#157]
When combining `.offset()` and `.limit()` with ActiveRecord, invalid SQL is generated:

`Product.limit(10).offset(5)` produces this invalid query:

```SELECT products.* FROM products OFFSET 5 ROWS FETCH FIRST 10 ROWS ONLY```

That leads to this error:

```
ActiveRecord::StatementInvalid (ActiveRecord::StatementInvalid: [IBM][CLI Driver][DB2/SUNX8664] SQL0104N  An unexpected token "5 ROWS" was found following "or inspect */ OFFSET".  Expected tokens may include:  "<space>".  SQLSTATE=42601 SQLCODE=-104)
```

This is the syntax that should be generated:

```SELECT products.* FROM products LIMIT 10 OFFSET 5```

`LIMIT` has to come before `OFFSET`.

I know that a while back I was the one asking to bring back the `FETCH FIRST ROWS ONLY` syntax because of my client's older DB2 version (see https://github.com/ibmdb/ruby-ibmdb/issues/136). The client was able to update to DB2 9.7 and was able to activate `OFFSET/LIMIT` support with these directions: https://programmingzen.com/enabling-limit-and-offset-in-db2-9-7-2/

Could I ask you to revert https://github.com/ibmdb/ruby-ibmdb/issues/136, making sure that a call like `Product.limit(10).offset(5)` will result in valid SQL? Thank you @praveen-db2

**Comment by praveen-db2** [comment]
@jfahrenkrug can you provide me sample test case which creates a table, inserts few rows and executes your test query which fails. It will be easy for me to proceed.

**Comment by jfahrenkrug** [comment]
@praveen-db2 Thank you for your as-always quick and kind response.

Calling `.limit(10).offset(5)` on any ActiveRecord model will produce the error. For example, in a fresh Rails project that is configured to use ibmdb in its database.yml file, run this command to create a `Post` entity:

`bin/rails generate model Post title:string body:text published:boolean`

Run the migrations

`bin/rails db:migrate`

Open the Rails Console:

`bin/rails c`

Run `Post.limit(10).offset(5)`. That should produce this SQL error:

```
ActiveRecord::StatementInvalid (ActiveRecord::StatementInvalid: [IBM][CLI Driver][DB2/SUNX8664] SQL0104N  An unexpected token "5 ROWS" was found following "or inspect */ OFFSET".  Expected tokens may include:  "<space>".  SQLSTATE=42601 SQLCODE=-104)
```

If you need more information, please let me know. Also, I've already prepared a PR here: https://github.com/ibmdb/ruby-ibmdb/pull/158

Thank you!

**Comment by praveen-db2** [comment]
@jfahrenkrug does PR #158 fix your problem ? If so I will merge the same.

**Comment by jfahrenkrug** [comment]
@praveen-db2 It *should* fix it, but it's completely untested. I just looked at the code and made the changes that I think are necessary. I'm sure your machine is set up for running the unit tests and verifying that it doesn't break anything. I would sleep much better at night if you could use your expert knowledge of this package to verify that it works and doesn't break anything.

**Comment by praveen-db2** [comment]
@jfahrenkrug ok then I need to test, I am between some other work blocked with that. I will start working on this later.

**Comment by jfahrenkrug** [comment]
Thank you very much! @praveen-db2

**Comment by jfahrenkrug** [comment]
@praveen-db2 I tried my changes locally and these are my results:

1. `DialogEntry.offset(5)` produces a valid SQL query:

```
[2023-07-24T10:03:27.708296 #15] DEBUG -- :   DialogEntry Load (88.2ms)  SELECT dialog_entries.* FROM dialog_entries /* loading for inspect */ LIMIT 11 OFFSET 5`
```
--> For some reason it defaults to `LIMIT 11`, when only `.offset()` is used. I'm not sure if that's some kind of ActiveRecord default, or if `.offset()` is not intended to be used without `.limit()`.

--

2. `DialogEntry.offset(5).limit(5)` works:

```
[2023-07-24T10:04:00.429971 #15] DEBUG -- :   DialogEntry Load (85.4ms)  SELECT dialog_entries.* FROM dialog_entries /* loading for inspect */ LIMIT 5 OFFSET 5
```

--

3. ` DialogEntry.offset(5).count` does not work (not sure if it's even a valid use case or not):

```
DialogEntry Count (155.5ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM dialog_entries OFFSET 5) subquery_for_count
Traceback (most recent call last):
        1: from (irb):5
ActiveRecord::StatementInvalid (ActiveRecord::StatementInvalid: [IBM][CLI Driver][DB2/SUNX8664] SQL0104N  An unexpected token "5" was found following "ialog_entries OFFSET".  Expected tokens may include:  "<space>".  SQLSTATE=42601 SQLCODE=-104)
```

**Comment by praveen-db2** [comment]
@jfahrenkrug my existing code works as per this DB2 documentation link 
https://www.ibm.com/docs/en/db2/11.5?topic=subselect-fetch-clause
https://www.ibm.com/docs/en/db2/11.5?topic=subselect-offset-clause 

**Syntax alternatives:** The following are supported for compatibility with SQL used by other database products. These alternatives are non-standard and should not be used. (as per documentation)
LIMIT x
LIMIT x OFFSET y
LIMIT y, x

**Comment by praveen-db2** [comment]
@jfahrenkrug I will work on this in my next release.

**Comment by praveen-db2** [comment]
@jfahrenkrug the last query you tried i.e "OFFSET only" case must be like below,
`select tabname from syscat.tables offset 5 rows`

Offset must end with rows/row. 
You can try the same.

I will do code changes accordingly.
From now on it will be "LIMIT x OFFSET y" syntax.
