### ISSUE TITLE
Enable GitHub Actions for CI and unit tests

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#159]
It would be great to enable and set up GitHub Actions to run the unit tests on every commit. I saw in the past that some significant changes (like this one https://github.com/ibmdb/ruby-ibmdb/pull/137/files) contained no changes to the unit tests. It would be great to run them automatically on GitHub Actions in order to increase the robustness.

**Comment by praveen-db2** [comment]
@jfahrenkrug Thats a good idea, thanks for your suggestion. Will work on this in my next release.

**Comment by praveen-db2** [comment]
Will close this, we will plan to have this in our pipeline.

**Comment by praveen-db2** [comment]
@jfahrenkrug pipeline means our work list planned for deliveries for next few months.
