### ISSUE TITLE
Fix unit tests and make them easier to run

### ISSUE THREAD

**Issue by jfahrenkrug** [ibmdb/ruby-ibmdb#160]
The current test suite doesn't work with the current version of Rails.
I tried to follow the steps here: https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/README#L126

I cloned the Rails repo and set up the "dev container" that's included.
I then ran a local DB2 DB with this command:

`docker run -h db2server --name db2server --restart=always --detach --privileged=true -p 50000:50000 --env-file .env_list -v /Users/johannes/Code/db2_docker:/database --platform linux/x86_64 icr.io/db2_community/db2`

I copied over the files into the `activerecord/test` directory and added `gem "ibm_db", path: "./ruby-ibmdb/IBM_DB_Adapter/ibm_db"` to the Gemfile.

Running `bundle exec rake test:ibm_db` first complained about `legacy_connection_handling`:

```
/workspaces/rails/activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `legacy_connection_handling=' for ActiveRecord::Base:Class (NoMethodError)
        from /workspaces/rails/activerecord/test/support/connection.rb:22:in `connect'
        from /workspaces/rails/activerecord/test/cases/helper.rb:27:in `<top (required)>'
        from /workspaces/rails/activerecord/test/cases/adapter_prevent_writes_test.rb:3:in `require'
        from /workspaces/rails/activerecord/test/cases/adapter_prevent_writes_test.rb:3:in `<top (required)>'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
```

After removing that in over 50 locations I ran it again and then got this error:

```
/workspaces/rails/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb:39:in `<module:ActiveRecord>': superclass mismatch for class SchemaMigration (TypeError)
        from /workspaces/rails/ruby-ibmdb/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb:38:in `<top (required)>'
        from /workspaces/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `require'
        from /workspaces/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
        from /workspaces/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
        from /workspaces/rails/activerecord/lib/active_record/connection_handling.rb:53:in `establish_connection'
        from /workspaces/rails/activerecord/test/support/connection.rb:26:in `connect'
        from /workspaces/rails/activerecord/test/cases/helper.rb:27:in `<top (required)>'
        from /workspaces/rails/activerecord/test/cases/adapter_prevent_writes_test.rb:3:in `require'
        from /workspaces/rails/activerecord/test/cases/adapter_prevent_writes_test.rb:3:in `<top (required)>'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from /usr/local/rvm/gems/default/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
```

It seems like maybe this test suite hasn't been run for a while. It would be great if we could update the instructions and maybe add a devcontainer to easily run these tests (start up a Docker community edition of DB2, set up the dev environment, and run the tests). Thoughts?

**Comment by praveen-db2** [comment]
@jfahrenkrug At present we support for Ruby <= 3.1.x and Rails 7.0.x.
Anything above is not yet supported. I am not sure what version of rails you are using. Current ibm_db release is been tested for Rails 7.0.x test suite.

**Comment by jfahrenkrug** [comment]
@praveen-db2 Good to know, thank you. I think I used a newer version of Rails, I might try it again with 7.0.x. Thanks! It would still be nice to be able to just run the tests in the project itself, without having to clone the Rails repo, copy the tests over to ActiveRecord, adjust some files, and then run them. I know this would be a bit of work, but it would be worth it, I think.

**Comment by praveen-db2** [comment]
Proposal is similar to https://github.com/ibmdb/ruby-ibmdb/issues/159,  Will close this now.
