### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by bnadav** [ibmdb/ruby-ibmdb#167]
Using Informix 14 database, Rails 7.0.8.1
I issue this command 

  `Chapter.first`

Which produces the following sql statement apparently not compatible with Informix:

 ` SELECT chapters.* FROM chapters ORDER BY chapters.chapter_ik DESC  FETCH FIRST 1 ROWS ONLY
`
[IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201 (ActiveRecord::StatementInvalid)

**Comment by praveen-db2** [comment]
@bnadav @oeil2lynx this fix already exist in adapter code (master branch) , but we are yet to release. In few days I will be releasing support for ruby 3.2 and rails 7.1. It should have that fix.

**Comment by oeil2lynx** [comment]
> @bnadav @oeil2lynx this fix already exist in adapter code (master branch) , but we are yet to release. In few days I will be releasing support for ruby 3.2 and rails 7.1. It should have that fix.

@praveen-db2 : I have a new error with the branch master

ActiveRecord::StatementInvalid: [IBM][CLI Driver][IDS/UNIX64] A syntax error has occurred. SQLCODE=-201
"SELECT appconfig.* FROM appconfig ORDER BY appconfig.confsn desc LIMIT 30 OFFSET 0"

on Rails 7.0.8.4 [Ruby ](ruby:2.7.8)

**Comment by praveen-db2** [comment]
@oeil2lynx offset clause doesnt exist on Informix server hence error, I will check if I can give fix for it in current release itself.
