### ISSUE TITLE
IDS compatability issues

### ISSUE THREAD

**Issue by bnadav** [ibmdb/ruby-ibmdb#168]
Occasionally the adapter issues statements like this:
`  SELECT tabname FROM (SELECT tabname, type FROM syscat.tables  WHERE tabschema = 'XXX') subquery `

I guess this is compatible with Db2 but is not compatible with Informix (IDS)

**Comment by praveen-db2** [comment]
@bnadav upcoming release has fix for this.

**Comment by praveen-db2** [comment]
closing this as recent release has fix for this
