### ISSUE TITLE
Readme specifies Ruby 3.1.x, which has ended normal maintenance

### ISSUE THREAD

**Issue by matthewkrom** [ibmdb/ruby-ibmdb#169]
Ruby 3.1.x, which is mentioned as the highest compatible version in the Readme, ended normal maintenance on April 1 2024 per https://www.ruby-lang.org/en/downloads/branches/

Can a maintainer test against Ruby 3.2 and 3.3 (which should run fine with Rails 7.0), and upgrade the Readme if compatible?  This can be thought of as an issue separate to supporting Rails 7.1 (also important).  Thank you!

**Comment by praveen-db2** [comment]
@matthewkrom by this week end I would be releasing support for Ruby 3.2 and Rails 7.1

**Comment by praveen-db2** [comment]
Closing this as support for ruby 3.2 is done.
