### ISSUE TITLE
rake db:migrate throwing error

### ISSUE THREAD

**Issue by tbagchi85** [ibmdb/ruby-ibmdb#17]
My PC is 64-bit Linux platform. Rails version I am using 4.1.1 . While I was trying to run rake db:migrate it throwing following error:-

_ruby /home/tanmay/.rvm/gems/ruby-2.2.0/bin/rake db:migrate: symbol lookup error: /home/tanmay/.rvm/gems/ruby-2.2.0/gems/ibm_db-2.5.18/lib/ibm_db.so: undefined symbol: rb_thread_blocking_region_

My LD_LIBRARY_PATH is follow:-

_/home/tanmay/sqllib/lib64/gskit:/home/db2inst1/sqllib/lib64:/home/db2inst1/sqllib/lib64/gskit:/home/db2inst1/sqllib/lib32_

thanks in advance

**Comment by arvindgu** [comment]
Hi,
I have not got a chance to run the gem with Ruby-2.2.x and recommend you to go with ruby-2.1.

Thanks,
Arvind

**Comment by tbagchi85** [comment]
Hi Arvind,

I installed Ruby-2.1.0 and the earlier error has gone. Now my migration is running.

thanks,
Tanmay

**Comment by arvindgu** [comment]
Today we have released new version of ibm_db gem that supports both Rails 4.2 and Ruby 2.2.  The new version of ibm_db gem is 2.5.25.

**Comment by dennisbaskin** [comment]
:smile: Thank you
