### ISSUE TITLE
Error when using .uniq

### ISSUE THREAD

**Issue by onordgren** [ibmdb/ruby-ibmdb#18]
Hi, I get the following error when calling uniq on a relation

```
RuntimeError: Failed to execute statement due to: [IBM][CLI Driver][DB2/LINUXX8664] SQL0134N  Improper use of a string column, host variable, constant, or function "DESCRIPTION".  SQLSTATE=42907 SQLCODE=-134: SELECT DISTINCT reports.* FROM reports 
```

The code that causes the error is 

```
@reports = Report.uniq
```

The report table does have a description field which is of type text which might be causing this issue but I'm not sure.

Any thoughts?

**Comment by arvindgu** [comment]
Hi,
Yes the larger objects like "Text" datatype are not permitted in SELECT DISTINCT statement.
For more information  on this error, Please refer -http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.1.0/com.ibm.db2.luw.messages.sql.doc/doc/msql00134n.html

Thanks,
Arvind
