### ISSUE TITLE
Error trying to connect to Informix DB

### ISSUE THREAD

**Issue by jeremysenn** [ibmdb/ruby-ibmdb#19]
I'm doing some initial testing trying to connect to an Informix DB through the rails console, and I have installed the ibm_db gem. Here's what I have in database.yml:

```
adapter: ibm_db
host: 192.168.111.170
port: 1526
username: someuser
password: secret
database: trangateway
```

However, I get the following when trying to look at one of the tables via the console:

RuntimeError: Failed to connect to [trangateway] due to: uncaught throw :"Connection failed: [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: \"TCP/IP\".  Communication API being used: \"SOCKETS\".  Location where the error was detected: \"192.168.111.170\".  Communication function detecting the error: \"recv\".  Protocol specific error code(s): \"_\", \"_\", \"0\".  SQLSTATE=08001 SQLCODE=-30081"

All my database.yml credentials look good. On the Informix server I see the following error:

 -408 invalid message type received

Any suggestions? Thanks!

**Comment by stianh26** [comment]
@jeremysenn 

Have you enabled the DRDA port on the Informix server?
I had a similar issue caused not connecting through the DRDA port.
http://www.ibm.com/developerworks/data/library/techarticle/dm-1012dsclidriver/

Also you'll need to define the table owner as the schema: in database.yml to access existing tables painlessly.

Cheers,

stianh26

**Comment by jeremysenn** [comment]
stianh26

Thanks for getting back to me! The DBA is looking into enabling the DRDA
port.

However, for compliance reasons, I'm not sure we'll be able to use the
table owner user in database.yml. What sort of issues do you foresee with
that?

Thanks!

Jeremy

**Comment by stianh26** [comment]
Hi Jeremy,

You don't need to use the database owner as the user in database.yml - I would not recommend that at all.

You just need to add schema: database-owner as a separate line:

adapter: ibm_db
host: 192.168.111.170
port: 1526
username: someuser
password: secret
database: trangateway
schema: database-owner

Otherwise I predict you will run into similar problems to Issue#13.

Cheers,

Stian

**Comment by jeremysenn** [comment]
Hey Stian,

I greatly appreciate all your help! Thanks to you, we are now successfully
connecting to Informix. However, this is my first pass at using Informix,
and so excuse my naïveté.

I get the following in the ruby console when doing a simple find for an
existing record with ID 27445:

> Transaction.find(27445)
  Transaction Load (1.7ms)  SELECT FIRST 1  log_record.* FROM log_record
 WHERE log_record.sys_seq_nbr = ?
=> #<Transaction >

However, there is no result and the resulting SQL from the find method
doesn't seem correct (missing the ID). How do you recommend doing simple
queries?

Thanks much!

Jeremy

**Comment by stianh26** [comment]
This is exactly what Issue#13 is about, which I encountered the 1st time I tried to connect to Informix - so I know where you are coming from.

Did you add the schema: to database.yml?

For the queries - I think there are a few things missing, so you need to tweak you methods (if you are scaffolding to start with). model.limit and model.offset seems to be the best. But I have to admit I have not done much development on Informix yet.

Let me know how you go.

Cheers,

Stian

**Comment by jeremysenn** [comment]
Stian,

Yes, that was exactly it . Once I set the schema to the DB owner, all is
good:

adapter: ibm_db
host: 192.168.111.170
port: 1526
username: someuser
password: secret
database: trangateway
schema: myowner

Thank you very much for all your help on this!

Jeremy

**Comment by jeremysenn** [comment]
Stian,

I have been successful thus far doing all of this on CentOS 6.3. However,
when I try to install the ibm_db gem on CentOS 7.0.1406 I get the error
below. Have you had success on a CentOS 7 box?

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.0/bin/ruby -r
./siteconf20150303-26023-whwg5b.rb extconf.rb
extconf.rb:67: warning: already initialized constant DOWNLOADLINK
extconf.rb:43: warning: previous definition of DOWNLOADLINK was here
extconf.rb:155: warning: already initialized constant IBM_DB_HOME
extconf.rb:19: warning: previous definition of IBM_DB_HOME was here
extconf.rb:157: warning: already initialized constant IBM_DB_INCLUDE
extconf.rb:142: warning: previous definition of IBM_DB_INCLUDE was here
extconf.rb:158: warning: already initialized constant IBM_DB_LIB
extconf.rb:143: warning: previous definition of IBM_DB_LIB was here
Detected 64-bit Ruby

Detected platform - linux x86 64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the
DB2 client driver
creating gil_release_version
creating unicode_support_version
checking for SQLConnect() in -ldb2... yes
checking for gil_release_version... yes
checking for unicode_support_version... yes
creating Makefile
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You
may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/rvm/rubies/ruby-2.2.0/bin/$(RUBY_BASE_NAME)
        --with-IBM_DB-dir
        --without-IBM_DB-dir
        --with-IBM_DB-include
        --without-IBM_DB-include=${IBM_DB-dir}/include
        --with-IBM_DB-lib
        --without-IBM_DB-lib=${IBM_DB-dir}/lib
        --with-db2lib
        --without-db2lib
extconf.rb:232:in `libpathflag': uninitialized constant Config (NameError)
        from
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/mkmf.rb:2219:in
`create_makefile'
        from extconf.rb:247:in `<main>'

extconf failed, exit code 1

**Comment by stianh26** [comment]
I haven't tried on CentOS 7 (works fine on 6.6).

Do you have the dsdriver package installed?

IBM_DB_HOME would typically be /opt/ibm/db2/V10.5/dsdriver

Check you .profile and see if the db2profile script is sourced - that should set all the environment variables you need.
if not try to set IBM_DB_HOME to the dsdriver folder

If that does not help - i would look at the environment you currently have working and compare to the new one. Then try to replicate.

Cheers,

Stian

**Comment by mariobriggs** [comment]
@jeremysenn @stianh26 
 one of the nice improvements for great simplicity of install of the ibm_db in version 2.5.18 [1] was that ibm_db would automatically pull down a IBM ODBC/CLI bundle if needed. Therefore you don't need to find/install/configure the right version of IBM ODBC/CLI bundle and every time keep sourcing the db2profile (yeah we will be happy with a thank you note for this great simplification :-))

So in jeremy's case above this has kicked in - 'Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver'.

I googled around for 'libpathflag' which is the error u are hitting and found this - https://bugs.ruby-lang.org/issues/9386 which could be the reason for the error. What version of ruby u are on in centos 7?

**Comment by stianh26** [comment]
We are very grateful for the very simplified installation process in version 2.5.18 ;-)
I can't get it to work on Mac though (which is why I had to set up the centos box in the first place).

**Comment by mariobriggs** [comment]
You are right that in 2.5.18 this doesn't apply to Mac OS - there wasn't a DS Driver/ODBC CLI package for Mac OS available at the time (and also windows - no support for -rpath with $ORIGIN. but we found other tricks). While beta's are being made available of these packages on Mac, ruby_ibm_db will also be enhanced in future... until then the option is to install DB2 Express-C on Mac to get the package (i can see the irony given u are using Informix )

**Comment by jeremysenn** [comment]
Extremely grateful for the simple install process! Thanks for the link.
However, I'm not sure what the fix may be.

I've tried installing with both ruby 2.2.0 and 2.1.2, to no avail.

**Comment by mariobriggs** [comment]
what's ur ruby version on CentOS 6.3 ?

**Comment by mariobriggs** [comment]
if you are interested in trying the macOS beta i mentioned above, drop me a note on my email ID noted on my github profile

**Comment by jeremysenn** [comment]
It's ruby 2.1.2 on CentOS 6.3

**Comment by stianh26** [comment]
Hi Jeremy,

I suggest you remove RVM completely, then do a full reinstall.
The bug causing the issue appear to be in the Ruby trunk an I am not sure if this gets reinstalled if you are just upgrading your ruby version.

Not sure if it will work, but should be worth a try.

**Comment by jeremysenn** [comment]
Hey Stian,

It looks like the adapter is treating all Informix smallint data types as
booleans in Ruby. Do you know how we can circumvent this?

Thanks!

Jeremy

**Comment by stianh26** [comment]
Hi Jeremy,

Have a look at ibm_db_adapter.rb line 309 or thereabouts. 

You should be able to change the mapping from smallint to boolean to be what you need.

Just keep in mind that if you reinstall the gem or upgrade it, your change will be overwritten (or at least I assume it will).

Cheers,

Stian

**Comment by jeremysenn** [comment]
I ended up just changing the column to an integer type in Informix for now.
Thanks for the help!

Jeremy

**Comment by arvindgu** [comment]
As the connection issue is resolved and there is a workaround to change the column type to integer to avoid smallint data treated as booleans. Hence closing this.
