### ISSUE TITLE
Compability with ISO-8859-1

### ISSUE THREAD

**Issue by viniciusoyama** [ibmdb/ruby-ibmdb#2]
Hi. I have a database that is all encoded with ISO-8859-1 and I'm using rails and having a problem with accentuation.
```ruby
sql = "select * FROM users WHERE name='zé'"
 stmt = ActiveRecord::Base.connection.execute(sql)
 res = IBM_DB.fetch_row(stmt)
```

This code returns false even if there is a user named 'zé'.

Looking at the source code I didn´t find any reference for ISO-8859-1. Can you guys please help me with that?
I'm using
 gem 'ibm_db', '2.5.11'
'rails', '3.2.17'

Thanks!

**Comment by zjuanma** [comment]
Hi @praveend, @viniciusoyama , do you have any solution on that?

**Comment by arvindgu** [comment]
@viniciusoyama  Which version of ruby you are using? Can you please try in latest version of ruby, rails and ibm-db gem and confirm that you still have this problem?

In my test I successfully executed the SQL statement mentioned in this issue with ruby irb. I tested on windows, ruby 2.2 and ibm_db gem version 2.5.27.  Also I tested on ruby 1.9.2 and ibm_db version 2.5.15. Here is the output I get

C:\Users\IBM_ADMIN>irb
irb(main):001:0> require 'mswin32/ibm_db'
=> true
irb(main):002:0> conn = IBM_DB.connect('sample','','')
=> #<IBM_DB::Connection:0x266de28>
irb(main):003:0> stmt = IBM_DB.exec conn,'select * from t1'
=> #<IBM_DB::Statement:0x2de1120>
irb(main):004:0> IBM_DB.fetch_assoc stmt
=> {"ID"=>1, "NAME"=>"z\u00E9"}

**Comment by zjuanma** [comment]
Hi, i found a solution.

WRONG QUERY

```
irb(main):001:0> SigningParty.where('surname like u&?', 'García')
  SigningParty Load (21.4ms)  SELECT signing_parties.* FROM signing_parties  WHERE (surname like u&'Garcia') 
RuntimeError: Failed to execute statement due to: [IBM][CLI Driver][DB2/LINUXX8664] SQL0007N  The character "&" following "HERE (surname like u" is not valid.  SQLSTATE=42601 SQLCODE=-7: SELECT signing_parties.* FROM signing_parties  WHERE (surname like u&'García') 
ActiveRecord::StatementInvalid: RuntimeError: Failed to execute statement due to: [IBM][CLI Driver][DB2/LINUXX8664] SQL0007N  The character "&" following "HERE (surname like u" is not valid.  SQLSTATE=42601 SQLCODE=-7: SELECT signing_parties.* FROM signing_parties  WHERE (surname like u&'García') 

  ```

CORRECT QUERY
```
irb(main):001:0> SigningParty.where('surname like (u&?)', 'García')
  ```

**Comment by zjuanma** [comment]
Show #34
