### ISSUE TITLE
Ruby 2.2.0: Error when trying to use ibm_db on Mac OS X

### ISSUE THREAD

**Issue by cyber-bug** [ibmdb/ruby-ibmdb#20]
We are currently developing a rails application and are trying to get the ibm_db gem running on ruby 2.2.0. The ibm_db gem was installed successfully and we've patched #15. We use a Mac OS X (yosemite) system as development/testing machine.

We are facing the following error message as we load the page of our rails application:
```
dyld: lazy symbol binding failed: Symbol not found: _rb_thread_blocking_region

  Referenced from: /path/to/.rvm/gems/ruby-2.2.0/gems/ibm_db-2.5.18-x86_64-darwin-14/lib/linux/rb20x/ibm_db.bundle

  Expected in: flat namespace
```

We looked into that and found several threads with kind of the same issue. The problem is that `rb_thread_blocking_region` is no longer supported in ruby 2.2 (see https://github.com/phusion/passenger/issues/1314 and https://github.com/ruby/ruby/blob/1c87fee3166c5208e92f1b7779507dd52c3087e1/NEWS) and has been removed.
 
`rb_thread_blocking_region` 

Was removed and replaced by:

`rb_thread_call_without_gvl`

We will try to fix this in the `ibm_db.c` and I will edit this post as soon as I have more insight.

May it help us to change this function call in `ibm_db.c` and compile the ibm_db gem by hand?

Best,
Bug

**Comment by arvindgu** [comment]
Hi,
Yes, we have analyzed the same that rb_thread_blocking_region is no more supported in Ruby 2.2. 
This needs to change to rb_thread_call_without_gvl in ibm_db.c. We are in the process of testing the changes and soon we will be releasing the code. 

Thanks,
Arvind

**Comment by arvindgu** [comment]
Today we have released new version of ibm_db gem that has support for both Rails 4.2 and Ruby 2.2.  The new version of ibm_db gem is 2.5.25.
