### ISSUE TITLE
Version 2.5.25 fails to install on Mac OS X

### ISSUE THREAD

**Issue by zambon** [ibmdb/ruby-ibmdb#23]
**OS**
Mac OS X Yosemite 10.10.2 (Darwin 14.1.0)

**Command**
```shell
$ gem install ibm_db -v '2.5.25'
```

**Error**
```
linking shared-object ibm_db.bundle
ld: unknown option: -R$ORIGIN/clidriver/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ibm_db.bundle] Error 1

make failed, exit code 2
```

Apparently OS X's `ld` does not have the `-R` option. Please let me know if you need more details.

**Comment by mariobriggs** [comment]
In 2.5.18/17 , there were separate prebuilt versions of the gem for MacOS. I dont think this has been done for 2.5.25 yet or has it been ugraded to automatically download of CLI client and link to that on Mac OS. The latter is on @arvindgu todo list, until then a prebuilt binary for MacOS should be provided

**Comment by leonsp** [comment]
I'm just starting a new Rails 4.2 project on Ruby 2.2 in a Mac development environment. Is there an ETA for updated ibm_db gem availability?

**Comment by arvindgu** [comment]
@leonsp we are working on it and we will be releasing updated ibm_db gem for Mac in next couple of days.

**Comment by arvindgu** [comment]
@leonsp  while working on to support Ruby 2.2 for Mac, we are running in to *Segmentation fault* error which seems to be originating from ruby itself. I have opened a separate issue for it [ibm_db gem do not support Ruby 2.2.x on Mac OS X] (https://github.com/ibmdb/ruby-ibmdb/issues/24) to track and provide further updates.

**Comment by JESii** [comment]
Is there an update on this issue or a recommended course of action while waiting for a resolution?

**Comment by arvindgu** [comment]
We have released gem version 2.5.27 with support of ruby 2.2 on Mac OS, Please use this version.

**Comment by JESii** [comment]
Just tried it and got the following error (same as 2.25.26); I did get 2.25.18 to install, but it threw a segfault when running.
```
compiling ruby_ibm_db_cli.c
linking shared-object ibm_db.bundle
ld: unknown option: -R$ORIGIN/clidriver/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ibm_db.bundle] Error 1

**Comment by zambon** [comment]
Version 2.5.27 installed successfully for me, but the driver will actually work only if I add `AUTHENTICATION=SERVER;` in the connection string (or `authentication: server` in `config/database.yml` for Rails apps).

**Comment by arvindgu** [comment]
How you install? By running <i>gem install ibm_db</i> command or some other way?
Also please confirm when you install with above command gem gets installed with named as <i>ibm_db-2.5.27-x86_64-darwin-14</i> in your Mac OS platform?

**Comment by zambon** [comment]
I used Ruby 2.2.1 and installed it with `gem install ibm_db`. 

```shell
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

$ gem list | grep ibm_db
ibm_db (2.5.27 x86_64-darwin-14)

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
```

**Comment by JESii** [comment]
I tried both `gem install ibm_db` and `bundle install` with the same results. I have since replaced rbenv with rvm and `bundle install` worked then... I have no idea why.

**Comment by zambon** [comment]
Another important detail I just remembered is that I installed IBM's Data Server Driver Package (DS Driver) in my Mac, and set the following environment variables in my `~/.profile`.
```
## IBM DB2
export IBM_DB_HOME=/Applications/dsdriver
# https://github.com/ibmdb/ruby-ibmdb/issues/29
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$IBM_DB_HOME/lib"
```

**Comment by arvindgu** [comment]
In our latest release of ibm_db gem version 2.6.0 onwards, we have enhanced installation for MacOS to pull IBM DB2 CLI bundle automatically and sets DYLD_LIBRARY_PATH itself.

**Comment by bhuten** [comment]
I am trying to connect to remote db2 using ibm_db gem. I installed the gem successfully but getting runtime error saying the adapt/driver is missing. What is the simplest way to solve this issue?

**Comment by arvindgu** [comment]
@bhuten could you please provide the steps you are following and the exact error message that you get when you try to connect.

**Comment by bhuten** [comment]
@arvindgu - I am using ruby 2.2.2 and Rails 4.2.1 on Mac OS 10. 

I simple added gem 'ibm_db' in my Gemfile and ran bundle install. The gem installation was successful with ibm_db (2.6.1 universal-darwin-14) installed. I updated my database.yml file with correct hostname, port, login and password. Finally I started my rail server but when I access localhost:3000, I get the following error:

Failed to connect to [myAp_dev] due to: uncaught throw :"Connection failed: [IBM][CLI Driver] SQL1042C An unexpected system error occurred. SQLSTATE=58004 SQLCODE=-1042"

Do I need to install any driver/adapter or need to set up any environment to use ibm_db gem? As I mentioned, I am using a remote db2 database.

Thanks a lot!

**Comment by bhuten** [comment]
I figured that the port was incorrect. I switched to 446 and now it is complaining about wrong database name. I will update when I figure out the db name. I am working on a legacy db2.

**Comment by bhuten** [comment]
@arvindgu - I am now having issues with licensing. I read in this thread https://github.com/ibmdb/ruby-ibmdb/issues/25 about licensing requirement but it wasn't very clear. What would be my next step? 

Lets say I get the license, what configuration set up I need to do? Again, I am simply using ibm_db gem on Mac OS X.

**Comment by arvindgu** [comment]
@bhuten Once you get the license file, you will need to just copy it in <ibm_db gem installation directory>/lib/clidriver/license
