### ISSUE TITLE
Load Error : ibm_db-2.5.26-x86-mingw32/lib/mswin32/rb19x/ibm_db.so (Windows 7 - ibm_db-2.5.26-x86-mingw32 )

### ISSUE THREAD

**Issue by balagod** [ibmdb/ruby-ibmdb#26]
<b>Environment:</b>
$ gem environment
RubyGems Environment:
- RUBYGEMS VERSION: 1.8.28
- RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [i386-mingw32]
- INSTALLATION DIRECTORY: c:/ruby-1.9.3/lib/ruby/gems/1.9.1
- RUBY EXECUTABLE: c:/ruby-1.9.3/bin/ruby.exe
- EXECUTABLE DIRECTORY: c:/ruby-1.9.3/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-mingw32
- GEM PATHS:
  - c:/ruby-1.9.3/lib/ruby/gems/1.9.1
  - c:/Users/1472947/.gem/ruby/1.9.1
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

<b>Error details:</b>
$ ruby db2test.rb
c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require': 193: %1 is not a valid Win32 application.   - c:/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/ibm_db-2.5.26-x86-mingw32/lib/mswin32/rb19x/ibm_db.so (LoadError) 
        from c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require' 
        from c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require' 
        from c:/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/ibm_db-2.5.26-x86-mingw32/lib/mswin32/ibm_db.rb:2:in`<top (required)>' 
        from c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require' 
        from c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in`rescue in require' 
        from c:/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from db2test.rb:2:in`<main> 

<b>Code</b> 

require 'rubygems'
require 'mswin32/ibm_db'

conn = IBM_DB.connect("DRIVER={IBM DB2 ODBC DRIVER};DATABASE=RMALL;\
                       HOSTNAME=ip;PORT=50000;PROTOCOL=TCPIP;\
                                              UID=usr;PWD=pass;", "", "")
       if conn
              puts "We're connected!"
        IBM_DB.close(conn)
       else
          puts "There was an error in the connection: #{IBM_DB.conn_errormsg}"
       end

**Comment by arvindgu** [comment]
Do you have IBM Data Server Driver 32-bit installed? If yes, you should have its bin directory path added in system variable PATH. for example -  *C:\Program Files (x86)\IBM\IBM DATA SERVER DRIVER\bin;*
Also you should create a environment variable IBM_DB_HOME and set it to the IBM Data Server Driver installation directory for example *C:\Program Files (x86)\IBM\IBM DATA SERVER DRIVER*

**Comment by balagod** [comment]
I have IBM Data studio installed in machine. can u tell me it will contain data drivers?
Able to connect using data studio DB SERVER version 8.1
IBM folder details:
![ibm](https://cloud.githubusercontent.com/assets/3187257/7087078/1f2be0c8-dfa5-11e4-9828-41709ad76623.png)

**Comment by arvindgu** [comment]
The DB2 SERVER version 8.1 is out of support. Use the latest version of DB2.

It is recommended to use latest version of ibm_db gem.

Use below connection string to connect
conn = IBM_DB::connect('hostname=<hostname>;port=<port>;UID=<user>;PWD=<password>;database=<databaseName>;,'','')
