### ISSUE TITLE
Library not loaded: /Users/mario/sqllib/lib64/libdb2.dylib (LoadError)

### ISSUE THREAD

**Issue by leonsp** [ibmdb/ruby-ibmdb#29]
I'm getting the error below with ibm_db 2.5.26 on Mac. I think the issue may be that "/Users/mario/" is hardcoded somewhere. There is no user named Mario on my system.

    /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/ibm_db-2.5.26-universal-darwin-14/lib/ibm_db.rb:5:in `require': dlopen(/Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/ibm_db-2.5.26-universal-darwin-14/lib/linux/rb19x/ibm_db.bundle, 9): Library not loaded: /Users/mario/sqllib/lib64/libdb2.dylib (LoadError)
      Referenced from: /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/ibm_db-2.5.26-universal-darwin-14/lib/linux/rb19x/ibm_db.bundle
      Reason: image not found - /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/ibm_db-2.5.26-universal-darwin-14/lib/linux/rb19x/ibm_db.bundle
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/ibm_db-2.5.26-universal-darwin-14/lib/ibm_db.rb:5:in `<top (required)>'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `require'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `each'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:72:in `block in require'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `each'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler/runtime.rb:61:in `require'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/bundler-1.9.4/lib/bundler.rb:134:in `require'
    	from /Users/leonsp/Projects/IMCloudAPI/config/application.rb:7:in `<top (required)>'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.12/lib/rails/commands.rb:21:in `require'
    	from /Users/leonsp/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.1.12/lib/rails/commands.rb:21:in `<top (required)>'
    	from script/rails:6:in `require'
    	from script/rails:6:in `<main>'

**Comment by mariobriggs** [comment]
On MacOS, the ibm_db gem does not yet automatically download the IBM DB2 CLI bundle and automatically link to it (still being worked on). Till then u need to 'export DYLD_LIBRARY_PATH=<sqllib\lib>

**Comment by arvindgu** [comment]
In our latest release of ibm_db gem version 2.6.0 onwards, we have enhanced installation for MacOS to pull IBM DB2 CLI bundle automatically.

**Comment by H-pratap** [comment]
Hi Arvind, I'm using ruby version 2.2.2 & ibm_db version 2.6.1 on mac. When i running Feature file on rubymine, i'm getting below error : 

dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/install_name_tool
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/install_name_tool
  Expected in: /usr/lib/libSystem.B.dylib

dlopen(/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle, 9): Library not loaded: libdb2.dylib
  Referenced from: /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle
  Reason: image not found - /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle (LoadError)
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.rb:18:in `require'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.rb:18:in `<top (required)>'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/Admin/git/QAA/support/common/env.rb:2:in `<top (required)>'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/rb_support/rb_language.rb:95:in `load'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/rb_support/rb_language.rb:95:in `load_code_file'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:82:in `each'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:184:in `load_step_definitions'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:42:in `run!'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/Admin/.rvm/gems/ruby-2.2.2/gems/cucumber-1.3.17/bin/cucumber:13:in `<top (required)>'
/Users/Admin/.rvm/gems/ruby-2.2.2/bin/cucumber:23:in `load'
/Users/Admin/.rvm/gems/ruby-2.2.2/bin/cucumber:23:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'

Process finished with exit code 1

**Comment by arvindgu** [comment]
Please check whether you have /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/clidriver/lib/libdb2.dylib present?

If it is present then below command to add libdb2.dylib in DYLD_LIBRARY_PATH.
export DYLD_LIBRARY_PATH=/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/clidriver/lib:$DYLD_LIBRARY_PATH

If it is not present then try re-installing ibm_db gem with sudo.

**Comment by H-pratap** [comment]
Arvind, i 've done all the action that you mentioned above in your comments , i mean i have 'libdb2.dylib' file present in lib directory and also i have set the export DYLD_LIBRARY_PATH in my bash_profile.But still getting the same error is coming. Kindly suggest

**Comment by arvindgu** [comment]
Can you open irb.  and try running require 'ibm_db'.  want to know if this also fails.

**Comment by H-pratap** [comment]
i opened the irb & run this command require 'ibm_db', but getting this error:

MACPRO40:~ Admin$ irb
2.2.2 :001 > require 'ibm_db'
dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/install_name_tool
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/install_name_tool
  Expected in: /usr/lib/libSystem.B.dylib

LoadError: dlopen(/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle, 9): Library not loaded: libdb2.dylib
  Referenced from: /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle
  Reason: image not found - /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.rb:18:in `<top (required)>'
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /Users/Admin/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'
2.2.2 :002 >

**Comment by arvindgu** [comment]
This does not seems to an issue with ibm_db gem. 
It could be possible that you may have Ruby installed in two place.  Refer [this ](http://stackoverflow.com/questions/22025160/dyld-lazy-symbol-binding-failed-symbol-not-found-ruby-run-when-using-heroku)to see if it can help you.

**Comment by H-pratap** [comment]
But issue is pointing to this one also:
LoadError: dlopen(/Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle, 9): Library not loaded: libdb2.dylib
Referenced from: /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle
Reason: image not found - /Users/Admin/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.6.1-universal-darwin-14/lib/ibm_db.bundle

I will refer the respective link that you provided  but for the 'image not found' : idm_db.bundle issue what i do
