### ISSUE TITLE
How to locally build ibm_db gem

### ISSUE THREAD

**Issue by thd-rental-team** [ibmdb/ruby-ibmdb#32]
I have a local checkout of the gem which I am customizing. Id like to pack the gem and use it on my project however there are some unexpected differences.

```
$ cd ~/workspace/ruby-ibmdb/IBM_DB_Adapter/ibm_db
$ gem build IBM_DB.gemspec.MacOS # produces .gem file
```

When I use this gem I get:
```
~/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- ibm_db.so
```

After unpacking both the original working gem and the one I built myself, I quickly noticed a difference between the files within the gem.

Original gem:
```
$ cd vendor/cache/ibm_db-2.5.26-universal-darwin-14/lib
$ cat IBM_DB.rb # shows https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/IBM_DB.rb.MacOS
$ cat IBM_DB.rb.MacOS # this does not exist
```

Gem I built myself:
```
$ cd vendor/cache/ibm_db-2.5.26-universal-darwin-14/lib
$ cat IBM_DB.rb # shows https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/IBM_DB.rb
$ cat IBM_DB.rb.MacOS # this exists
```

How do I build the gem correctly?

**Comment by arvindgu** [comment]
The IBM_DB.rb.MacOS and IBM_DB.gemspec.MacOS files are for Mac OS specific. 

To build the IBM_DB gem on Mac OS, you need to remove existing contents of IBM_DB.rb and IBM_DB.gemspec and copy the contents from IBM_DB.rb.MacOS and IBM_DB.gemspec.MacOS respectively.

Before building the gems, you need to generate binary for ibm_db.bundle under IBM_DB_Driver directory via running command ruby extconf.rb  After binary is generated successfully, copy it to IBM_DB_Adapter\ibm_db\lib\linux\rbXXX directory. Here rbXXX is the version of ruby you have used to generate the binary. 
After this run gem build IBM_DB.gemspec to produce the gem file. 

Please let us know if you still having problem.

**Comment by thd-rental-team** [comment]
Thanks for the clarifiation.

I notice you have many rbXXX directories, do you "make" using each ruby version manually? Or is this automated somewhere?

**Comment by arvindgu** [comment]
Yes we generate binary for ibm_db.bundle manually for each ruby version and copy them to respective rbXXX directories.

**Comment by thd-rental-team** [comment]
In regards to building the gem on OSX, do you have the steps to build the gem manually? I see the extconf.rb does not explicitly support osx, I placed the download link in the file and attempted to make but it would not work.

```
DOWNLOADLINK = "http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz"
```

```
$ make

...

linking shared-object ibm_db.bundle
ld: unknown option: -R$ORIGIN/clidriver/lib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ibm_db.bundle] Error 1
```

**Comment by thd-rental-team** [comment]
I got the make working, I had to change a line in the Makefile

Changed:

```
LIBPATH =  -L. -L$(libdir) -L/Users/user/workspace/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib '-Wl,-R$$ORIGIN/clidriver/lib'
```

to

```
LIBPATH =  -L. -L$(libdir) -L/Users/user/workspace/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib '-L/Users/user/workspace/ruby-ibmdb/IBM_DB_Adapter/ibm_db/ext/../lib/clidriver/lib'
```

**Comment by arvindgu** [comment]
In latest release of ibm_db gem version 2.6.0 onwards, we have simplified installation for MAC OS, and you do not need to follow the manual steps as mentioned above.
