### ISSUE TITLE
Accessing DB2 server on OSX throws "Connection failed" error

### ISSUE THREAD

**Issue by JESii** [ibmdb/ruby-ibmdb#33]
Running `ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]` and `ibm_db (2.5.26 universal-darwin-14)`. 
Attempting to read from DB2 database throws error: 
`ERROR - DATA: eval failed to return, and generated an exception: Failed to connect to [mlq10] due to: uncaught throw :"Connection failed: [IBM][CLI Driver] SQL10007N Message \"0\" could not be retrieved.  Reason code: \"3\". SQLCODE=-1390" (RuntimeError)`. 
Any suggestions?

**Comment by arvindgu** [comment]
This seems to some problem in data server. To isolate the problem, could you please try connecting to any other database from ruby. You can also try to connect via db2 CLI to verify connectivity.

**Comment by JESii** [comment]
Sorry; been buried. I'll try to take a look this weekend. Thanks

**Comment by JESii** [comment]
Sorry; I lost track of this in the delivery crunch. As I recall, I had to reconfigure my ENV variables : they were pointing to things incorrectly because of OSX changes in DYLD-path support. What I have now is:
```
export DB2HOME=/Users/db2inst1/sqllib
export DYLD_LIBRARY_PATH="$DB2HOME/lib64:$ORACLE_HOME:$DYLD_LIBRARY_PATH"
export IBM_DB_HOME=$DB2HOME
```

Probably more than is needed, but it's working for me.
