### ISSUE TITLE
Error with ISO-8859-15 and Rails 4.2, Arel 6.0, ibmdb 2.5.27 

### ISSUE THREAD

**Issue by zjuanma** [ibmdb/ruby-ibmdb#34]
Hi,

i have found a error when database has codepage set to 923 (iso-8859-15) in Rails 4.2 and ibmdb 2.5.27.

Show this example:

```
require 'ibm_db.so'
conn_string = 'DRIVER={IBM DB2 ODBC DRIVER};DATABASE=develop;HOSTNAME=db2;PORT=50000;PROTOCOL=TCPIP;UID=db2inst1;PWD=db2inst1;'
conn = IBM_DB.connect(conn_string, 'db2inst1', 'db2inst1')
IBM_DB::exec conn,"Insert into companies (name, code) values('García','006')"

stmt = IBM_DB.prepare(conn, "Insert into companies (name, code) values(?,?)")
values = [ "García", "101" ]
IBM_DB.execute(stmt,values)
```

Data in database table:

```
NAME	CODE	
GarcÃ­a 006 		-> INCORRECT
García  101      -> CORRECT
```

**Comment by arvindgu** [comment]
Hi,
To resolve this problem, 
(1). you need to set <b>DisableUnicode</b> keyword to <b>1</b> in IBM data server driver configuration (db2dsdriver.cfg) file.
<parameter name="DisableUnicode" value="1"/>  

(2). You also need to add below line in your ruby code.
<b>#encoding: ISO-8859-15</b>

Please refer below link to know more about <i>DisableUnicode</i> keyword.
http://www-01.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.swg.im.dbclient.config.doc/doc/r0054636.html?cp=SSEPGG_10.5.0%2F2-0-2-5-7-0-7-53&lang=en

**Comment by zjuanma** [comment]
In Rails only need step 1).

**Comment by altherlex** [comment]
[bug rails]Rails have problem with ISO app configuration.

So, you can use a project app configuration with utf-8 and connect DB2 configuration with ISO normaly!!!
