### ISSUE TITLE
Extract database driver from ActiveRecord adapter

### ISSUE THREAD

**Issue by thd-rental-team** [ibmdb/ruby-ibmdb#36]
Would it be difficult to create a separate gem that provides the IBM_DB library separate from the ibm_db/active_record adapter?  I think that would be valuable in our use-case since we're using the Sequel gem as our adapter instead of ActiveRecord.

**Comment by arvindgu** [comment]
Creating a new gem without ibm_db/active_record adapter won't be difficult, you can try it out.
