### ISSUE TITLE
remove_column appears to be using an old implementation

### ISSUE THREAD

**Issue by lrcrews** [ibmdb/ruby-ibmdb#4]
It appears that the gem is implementing a rather dated version of remove_column that only accepts two parameters:

remove_column :foo_table, :bar_column

as opposed to the version created for migrations utilizing the "change" method that accepts three columns:

remove_column :foo_table, :bar_column, :string

A work around for this is to not use the "change" method in your migrations that remove columns, but instead implement the older "up" and "down" methods.

While this isn't a huge issue I thought I'd bring it up just incase you want an excuse to work on rails stuff at IBM =]

**Comment by zjuanma** [comment]
Is it fixed?

**Comment by arvindgu** [comment]
@zjuanma, its not fixed yet. We will be fixing it in next version.

**Comment by arvindgu** [comment]
Please try the latest version of gem.
