### ISSUE TITLE
DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0.

### ISSUE THREAD

**Issue by leonsp** [ibmdb/ruby-ibmdb#41]
I'm getting the following deprecation warning running migrations with ibm_db on Rails 4.2.3:

    DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0.

It's breaking a migration that also creates an activerecord object with a text field. Here's an edited stacktrace:

    DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0. (called from create_ssh_key at /Users/leonsp/Projects/IMCloudAPI/app/models/user.rb:445)
    rake aborted!
    StandardError: An error has occurred, this and all later migrations canceled:

    undefined method `call' for :notice:Symbol
    ...
    NoMethodError: undefined method `call' for :notice:Symbol
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/reporting.rb:19:in `block (2 levels) in warn'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/reporting.rb:19:in `each'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/reporting.rb:19:in `block in warn'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/reporting.rb:18:in `tap'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/reporting.rb:18:in `warn'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/deprecation/instance_delegator.rb:19:in `warn'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/attribute_methods/serialization.rb:56:in `serialized_attributes'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.5.27-x86_64-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:98:in `block (2 levels) in handle_lobs'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.5.27-x86_64-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:82:in `each'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.5.27-x86_64-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:82:in `block in handle_lobs'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.5.27-x86_64-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:70:in `each'
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/ibm_db-2.5.27-x86_64-darwin-14/lib/active_record/connection_adapters/ibm_db_adapter.rb:70:in `handle_lobs'
    ...
    /Users/leonsp/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.4/lib/active_record/persistence.rb:142:in `save!'
    ...

Could you please refactor ibm_db to remove the deprecation warning?

**Comment by arvindgu** [comment]
Today we have released ibm_db gem version 3.0.0 and we have fixed this issue with deprecated serialized_attributes.

**Comment by arvindgu** [comment]
Can this be closed?

**Comment by leonsp** [comment]
Yes, it can be closed. Thanks!
