### ISSUE TITLE
Rails 4.2.4 Ruby 2.1.7 ibm_db-2.6.1-x86-mingw32 DB2 9.7.7 

### ISSUE THREAD

**Issue by marcomd** [ibmdb/ruby-ibmdb#42]
Hello,

I just started a new application with activeadmin gem and I get the below issue.
I cannot find the version of db2 request from drivers, could be this the problem or what else?

``` sql
RuntimeError: Failed to execute statement due to: [IBM][CLI Driver][DB2/AIX64] SQL0206N  "SYS_ROW_NUM" is not valid in the context where it is used.  SQLSTATE=42703
 SQLCODE=-206: SELECT O.* FROM (SELECT I.*, ROW_NUMBER() OVER () sys_row_num FROM ( SELECT  COUNT(count_column) FROM (SELECT  1 AS count_column FROM users ) AS I) AS O WHERE sys_row_num BETWEEN 1 AND 30) subquery_for_count
```

**Comment by marcomd** [comment]
The first step was to install the driver IBM Data Server Driver Package (Windows/x86-32 32 bit) V9.7
I dont know if it is necessary on linux but on windows yes otherwise the system get stuck after the first query.

Now it works except all index pages **because the error is on the count** and active admin use several count queries.
I get the error also in console when using the count, i'll show you below

Contract.limit(30).offset(0).all => **it works!!** :green_heart:
```sql
SELECT O.* FROM (SELECT I.*, ROW_NUMBER() OVER () sys_row_num FROM ( SELECT   contracts .* FROM contracts  ) AS I) AS O WHERE sys_row_num BETWEEN 1 AND 30
```

Contract.limit(30).offset(0).count => **oh oh** :broken_heart:
```sql
SELECT O.* FROM (SELECT I.*, ROW_NUMBER() OVER () sys_row_num FROM ( SELECT  COUNT(count_column) FROM (SELECT  1 AS count_column FROM contracts ) AS I) AS O WHERE sys_row_num BETWEEN 1 AND 30) subquery_for_count
```

_RuntimeError: Failed to execute statement due to: [IBM][CLI Driver][DB2/AIX64] SQL0206N  "SYS_ROW_NUM" is not valid in the context in which it is used.  SQLSTATE=42703_

**Comment by arvindgu** [comment]
With the newer version of ibm_db gem, Installation of IBM Data Server Driver Package is not necessary as while ibm-db gem installation, required files are downloaded itself and configured.

However this error is not related to  IBM Data Server Driver Package. We need to investigate the query generation. Could you please provide a simple repro that I can use to investigate this problem?

**Comment by arvindgu** [comment]
Count can not be combined with limit and offset. If you want to know total number of rows returned, You will need to run separate query for it.

**Comment by marcomd** [comment]
Hello,
i think it was a good idea to include drivers in the gem but in my case it didn't work, as i wrote the app server got stuck after first query.

About the main issue, count could be joined with every other finder methods. If you try other db driver you see it works.

**Comment by arvindgu** [comment]
At present we do not have plan to support Count with limit and offset.
