### ISSUE TITLE
error in IRB when requiring gem

### ISSUE THREAD

**Issue by ruby-dude** [ibmdb/ruby-ibmdb#48]
I have attempted to follow the applicable directions for installation and testing of the ibm_db gem.  When I open IRB and require the gem on my windows pc, I get the following errors:

irb(main):001:0> require 'mswin32/ibm_db'
Errno::ETIMEDOUT: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
. - connect(2) for "public.dhe.ibm.com" port 80
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:879:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        from C:/Ruby22/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:878:in `connect'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ibm_db-3.0.0-x86-mingw32/lib/mswin32/ibm_db.rb:24:in `downloadCLIPackage'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ibm_db-3.0.0-x86-mingw32/lib/mswin32/ibm_db.rb:69:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby22/bin/irb:11:in `<main>'

Is there a config file that I don't know about that needs to be updated?  Why is the gem attempting to connect to anything just when requiring?

Thanks.

**Comment by arvindgu** [comment]
For Windows, the ibm_db gem auto downloads the necessary CLI package when ibm_db gem is used first time. Please note, the download happens only once, if it was successful.

If you have firewall setup, please allow host public.dhe.ibm.com.

**Comment by ruby-dude** [comment]
This worked!  Thank you.  This would EXTREMELY helpful to know in the future.  Is it possible to have this added to the RDoc of the gem so people in the future know how to get this gem working?

**Comment by arvindgu** [comment]
Can we close this?

**Comment by ruby-dude** [comment]
yep, thanks!
