### ISSUE TITLE
update_attributes sets all clobs to '<ibm>@@@IBMTEXT@@@</ibm>'

### ISSUE THREAD

**Issue by leonsp** [ibmdb/ruby-ibmdb#49]
Regardless of what value you pass in for a clob, `update_attributes` will set the value to `<ibm>@@@IBMTEXT@@@</ibm>` in the database.

For example:

mm = MyModel.find(141)
mm.update_attributes(description: "Foo bar baz")
  SQL (0.7ms)  UPDATE my_models SET description = '<ibm>@@@IBMTEXT@@@</ibm>', updated_at = '2016-01-04 18:56:55.047075' WHERE my_models.id = 141
 => true

`update_attributes!` has the same behaviour, as does modifying the attribute and then calling `save`.

I'm using ibm_db 3.0.0 on Rails 4.2.4

**Comment by arvindgu** [comment]
Today, we have released *new* version of ibm_db gem **3.0.1**  and fixed this issue.. Please try this and let us know.

**Comment by leonsp** [comment]
I believe the issue is fixed by 3.0.1. Thanks!

**Comment by arvindgu** [comment]
Yes, we have fixed it in 3.0.1.
