### ISSUE TITLE
Create a sample application as an example

### ISSUE THREAD

**Issue by jonstorer** [ibmdb/ruby-ibmdb#54]
It would be helpful to create a sample rails/sinatra/ruby application that did the following:
- connected to db2-express-c
- connected to db2 on system-i
- provide an example of a working application in Windows, Linux, and OS X.
- show solutions for known work around listed in https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/README

**Comment by douglaslee1990** [comment]
Agreed ^^

**Comment by arvindgu** [comment]
Please refer this [blog](https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/Build_a_Ruby_on_Rails_web_application_with_IBM_DB2_zOS?lang=en)
