### ISSUE TITLE
bind_param error (STP) - Driver not capable

### ISSUE THREAD

**Issue by ruby-dude** [ibmdb/ruby-ibmdb#55]
I'm attempting to access a stored procedure through IBM_DB.  I've set my 'sql', which i set as the name of my stored procedure, and then also set my 'statement', which i called response.  Here is some info on what I set:

connection = IBM_DB.connect 'DB-name', 'username', 'password' (works fine)
stp = 'CALL stored procedure name(?,?,?,?,?,?,?,?,?)'
response = IBM_DB.prepare connection, stp

I then set my variables based on my calling needs:

a = 1234
b = 0
c = 1
d = 0
etc.

I then tried to bind the parameters and this is where it's failing and giving me an error I can't figure out:

warning: Describe Param Failed: [IBM][CLI Driver] CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999

What does that error mean??

I tried the commands below, trying just about every combination I could think of based on the documentation and what I found online.  The documentation labels the PARAM_INPUT as an INT but doesn't say what to pass so I'm using what you see below.  All lines fail and give me the same error.

IBM_DB.bind_param(response, 1, "a", IBM_DB::SQL_PARAM_INPUT)
IBM_DB.bind_param(response, 1, "a", 1)
IBM_DB.bind_param(response, 1, "a")

Using anything other than IBM_DB::SQL_PARAM_INPUT gives errors that there is no method found for IBM_DB:

IBM_DB.bind_param(response, 1, "a", IBM_DB.SQL_PARAM_INPUT)
IBM_DB::bind_param(response, 1, "a", IBM_DB::PARAM_IN)
IBM_DB.bind_param(response, 1, "a", IBM_DB::PARAM_IN)

If anyone has ANY information to help me through this issue or at least tell me what the error is trying to tell me, I'd greatly appreciate it!

**Comment by ruby-dude** [comment]
I have tried to establish a new connection with ActiveRecord with the following:

ActiveRecord::Base.establish_connection(:adapter => 'ibm_db', :database => 'database', :username => 'username', :password => 'password')

connb = ActiveRecord::Base.connection.connection
IBM_DB::prepare(connb,sql)

I then tried the 4 versions of the bind_param command again, all giving the same error: 
warning: Describe Param Failed: [IBM][CLI Driver] CLI0150E  Driver not capable. SQLSTATE=HYC00 SQLCODE=-99999

I used:
IBM_DB.bind_param(stmtb, 1, "a", IBM_DB::SQL_PARAM_INPUT)
IBM_DB::bind_param(stmtb, 1, "a", IBM_DB::SQL_PARAM_INPUT)
IBM_DB::bind_param(stmtb, 1, "a")
IBM_DB.bind_param(stmtb, 1, "a")

Perhaps once I know what the 'driver not capable' error refers to, I'll be able to move forward on the function.

**Comment by arvindgu** [comment]
The error could be due to the stored procedure, related tables are not present in the database you are connecting to. Please ensure that the stored procedure and related tables are created and present in the database t you are connecting to.

As an example, you can refer the test case - 
https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Driver/tests/test_52949_StoredProcedures.rb

**Comment by ruby-dude** [comment]
We figured out that we were missing the schema and not setting a placeholder for ALL parameters in the STP.  So in the end, this is what worked (we have 17 parameters):

sql = "CALL DB2.OUR_STP(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"

Thanks.

**Comment by arvindgu** [comment]
Can we close this?

**Comment by ruby-dude** [comment]
yes, thank you.
