### ISSUE TITLE
How Can I access resultset Data?  Rec'ing Error

### ISSUE THREAD

**Issue by ruby-dude** [ibmdb/ruby-ibmdb#56]
When calling a Stored Procedure, we are having trouble getting to the actual result set data.  IBM_DB::fetch_assoc(stmt) throws an error. In fact, all fetch functions do which leads me to believe that perhaps we are perhaps not calling/referencing the STP correctly.

The error: "UncaughtThrowError: uncaught throw :"Column information cannot be retrieved: <error message could not be retrieved>""

We are using the following settings:

connection = IBM_DB::connect db_env,$user_id, $user_pw
IBM_DB.set_option connection, {IBM_DB::SQL_ATTR_AUTOCOMMIT => IBM_DB::SQL_AUTOCOMMIT_OFF}, 1
sql = "CALL DB2.OUR_STP(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
stmt = IBM_DB::prepare connection, sql

We then set all 17 parameters using IBM_DB:bind_param.

The issue is that the result set that we get back is not just output from our initial input parameters.  There is a seperate result set that should be returned.  This is not an issue when calling SQL directly using IBM_DB:exec(stmt, some_sql).  It returns an array and is quite nice.  We were hoping to get the same by calling IBM_DB::fetch_assoc(stmt) but instead we get the error I mentioned.

Calling IBM_DB::columns(stmt) does return an object ( #<IBM_DB::Statement:0x8500d10>, for example), but we can't see the actual result set of that either.

Any ideas as to why we get this error when we call fetch_assoc(), fetch_array(), fetch_both(), result()?

If more information is needed let me know.

Thanks!

**Comment by arvindgu** [comment]
It would be very helpful and quick to investigate, if you can provide a simple repro alongwith stored procedure definition.

**Comment by ruby-dude** [comment]
Unfortunately, I cannot provide that data. It's proprietary for my company and cannot be distributed.  I'm just wondering if perhaps my call to the STP is flawed or what else could be causing the UncaughtThrowError.  I could not find that in the code on github.

any info is appreciated.

**Comment by arvindgu** [comment]
Here is an example, that you can refer to access result set from a stored procedure

**Stored procedure definition**
CREATE PROCEDURE Test1 (IN EMPID CHAR(6))
  DYNAMIC RESULT SETS 1
P1: BEGIN
       DECLARE cursor1 CURSOR WITH RETURN for
	SELECT * FROM EMPLOYEE where EMPNO = EMPID;
	OPEN cursor1;
END P1


**Ruby Code**

require 'mswin32/ibm_db'
conn = IBM_DB.connect('SAMPLE', 'userid','password')
sql = "CALL EMPDETAIL(?)"
stmt = IBM_DB::prepare conn, sql
empno="200340"
*##Please note we passed variable name that contains parameter input value in below statement*
IBM_DB::bind_param stmt, 1, "empno", IBM_DB::SQL_PARAM_INPUT
IBM_DB::execute(stmt)

**To retrieve you can use either of  *fetch_assoc* or *fetch_array* or *fetch_both* or *fetch_row* as below.**

if( row = IBM_DB.**fetch_assoc** stmt)
   printf("%s ",row['EMPNO'])
   printf("%s ",row['FIRSTNME'])
   printf("%s ",row['MIDINIT'])
   printf("%s",row['LASTNAME'])
   printf("%s ",row['WORKDEPT'])
   printf("%s ",row['PHONENO'])
   printf("%s ",row['HIREDATE'])
   printf("%s",row['JOB'])
   printf("%s ",row['EDLEVEL'])
   printf("%s ",row['SEX'])
   printf("%s ",row['BIRTHDATE'])
   printf("%s",row['SALARY'])
   printf("%s ",row['BONUS'])
   printf("%s ",row['COMM'])
end

---------------------------------

while (row = IBM_DB::**fetch_array**(stmt))
 row.each { |child| puts child }
end

---------------------------------

while (data = IBM_DB::**fetch_both** stmt)
   printf("%s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s\n", data[0], data[1], data[2], data[3], data[4], data[5], data[6], data[7], data[8], data[9], data[10], data[11], data[12], data[13], data[14]);
end

---------------------------------

while IBM_DB::**fetch_row**(stmt)
          col0 = IBM_DB::result stmt, 0
          col1 = IBM_DB::result stmt, 1
          col2 = IBM_DB::result stmt, 2
          col3 = IBM_DB::result stmt, 3
	  col4 = IBM_DB::result stmt, 4
	  col5 = IBM_DB::result stmt, 5
	  col6 = IBM_DB::result stmt, 6
	  col7 = IBM_DB::result stmt, 7
	  col8 = IBM_DB::result stmt, 8
	  col9 = IBM_DB::result stmt, 9
	  col10 = IBM_DB::result stmt, 10
	  col11 = IBM_DB::result stmt, 11
	  col12 = IBM_DB::result stmt, 12
	  col13 = IBM_DB::result stmt, 13
	  col14 = IBM_DB::result stmt, 14
          puts "#{col0} | #{col1} | #{col2} | #{col3} | #{col4} | #{col5} | #{col6} | #{col7} | #{col8} | #{col9} | #{col10} | #{col11} | #{col12} | #{col13} | #{col14}"
          end

**Comment by arvindgu** [comment]
Can we close this?
