### ISSUE TITLE
Selects not getting fully prepared

### ISSUE THREAD

**Issue by paulharv** [ibmdb/ruby-ibmdb#58]
We are using versions 2.6.1 and 3.0.1 and in both cases we are observing that select statements do not get fully prepared if the datatypes in a call to `Model.where` are mixed.

For example… 
These all produce fully prepared statements...

```
Model.where(“column1=? And column2=?”, 10, 20)      # ==> select * from model_table where column1=? And column2=?   # OK
Model.where(“column1=? And column2=?”, "Red", "Blue")   # ==> select * from model_table where column1=? And column2=?   # OK!
Model.where(“column1=? And column2=?”, "Red", "20")   # ==> select * from model_table where column1=? And column2=?     # OK!
```

But this, which has mixed datatypes in the parameter array, does not...

```
Model.where(“column1=? And column2=?”, "Red", 20)   # ==> select * from model_table where column1=? And column2=20  # BAD!
```

We're seeing this have significant impact on performance so would love to see it addressed!

Thanks very much,

Paul

**Comment by arvindgu** [comment]
I could not reproduce this problem. I have listed my reproduction steps below. Please provide me exact reproduction steps so that I can further investigate on it. 

rails generate scaffold Car name:string reg_num:integer year:integer features:string

I have run below steps using rails console.

car= Car.new
car.name='Skoda'
car.reg_num=1111
car.year=2014
car.features='Semi-Luxury'
car.save

car= Car.new
car.name='volkswagen'
car.reg_num=2222
car.year=2012
car.features='Luxury'
car.save

Car.where("reg_num=? and year=?", 2222, 2012)    #==> SELECT cars.* FROM cars WHERE (reg_num=2222 and year=2012) # OK
Car.where("name=? and features =?",'Skoda', 'Semi-Luxury')  #==>   SELECT cars.* FROM cars WHERE (name='Skoda'and features ='Semi-Luxury') # OK
Car.where("name=? And reg_num=?", 'Skoda', 1111)  #==>     SELECT cars.* FROM cars WHERE (name='Skoda' And reg_num=1111) # OK

**Comment by mcdonalduid** [comment]
If you examine the database statement cache you will see that the integers in the SQL is not prepared.
I use the Dynamic Statement screen in "db2top" to examine the database statement cache.

**Comment by mcdonalduid** [comment]
Along the same line If I set parameterized to true in the database.yml I get an error.

2.2.1 :001 > Car.where("reg_num=? and year=?",2222,2012)
TypeError: superclass mismatch for class HasOneAssociation
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:1169:in `<module:Associations>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:1140:in `<module:ActiveRecord>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:27:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_adapter.rb:163:in `ibm_db_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
... 13 levels...
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/rmcdonal/Projects/spotlight/bin/rails:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.1 :002 >

**Comment by arvindgu** [comment]
The IBM_DB adapter relies on the IBM_DB Ruby driver (C extension) and the IBM® Data Server Driver for ODBC and CLI to access databases on IBM data servers.

This behavior is as per designed i.e. parameter marker are applied ( i.e. ?)  only  for the values that comes as a string in CLI component. 

This has been considered as enhancement/feature request and it will be fiixed in future releases of CLI.

**Comment by mcdonalduid** [comment]
One a different note if I set parameterized to true in the database.yml, I get an error.
```
development:
  <<: *default
  parameterized: true
  reconnect:    true
  username:     test
  password:     test

```


2.2.1 :001 > Car.find(1)
TypeError: superclass mismatch for class HasOneAssociation
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:1169:in `<module:Associations>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:1140:in `<module:ActiveRecord>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_pstmt.rb:27:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/ibm_db-3.0.2/lib/active_record/connection_adapters/ibm_db_adapter.rb:163:in `ibm_db_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
... 11 levels...
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/rmcdonal/Projects/spotlight/bin/rails:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.1 :002 >

**Comment by mcdonalduid** [comment]
I went back and checked it worked under;
Ruby: 1.8.7
Rails: 2.3.14
DB2 Gem: 2.5.11

**Comment by arvindgu** [comment]
We have fixed it in ibm_db version 3.0.4. 

You will need to set "parameterized: true" in database.yml file and query and use below Rails APIs that generates prepared statement. Please notice how parameters are passed in below APIs.

Car.find(1) 
Car.find_by_id(1)
Car.find_by_reg_num(1111)
Car.find_by(:reg_num => 1111, :year =>2014)
Car.find_by(reg_num: 1111, features:'Semi-Luxury') 
Car.find_by(name: 'Skoda', reg_num:1111)
Car.find_by(name:'Skoda', features: 'Semi-Luxury')
Car.where(:id =>1)
Car.where(:reg_num =>1111)  
Car.where(:reg_num => 1111, :year =>2014) 
Car.where(:reg_num => 1111, :features =>'Semi-Luxury')  
Car.where(:name =>'Skoda', :reg_num =>1111)  
Car.where(:name=>'Skoda', :features=>'Semi-Luxury')  


FYI, below Rails APIs do not generate prepared statement. 
Car.find_by("reg_num=? and year=?", 1111, 2014)
Car.find_by("reg_num =? and features =?", 1111, 'Semi-Luxury')
Car.find_by("name=? And reg_num=?", 'Skoda', 1111)
Car.where("id=?", 1)
Car.where("reg_num=? and year=?", 1111, 2014)
Car.where("name=? and features =?",'Skoda', 'Semi-Luxury')
Car.where("name=? And reg_num=?", 'Skoda', 1111)

**Comment by mcdonalduid** [comment]
How would I do the following?

Car.find_by("reg_num=? and year!=?", 1111, 2013,)
2.1.8 :129 > Car.find_by(:reg_num => 1111, :year!=2014)
SyntaxError: (irb):129: syntax error, unexpected ')', expecting =>
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/rmcdonal/Projects/spotlight/bin/rails:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.1.8 :130 > Car.find_by(:reg_num => 1111, :year<>2014)
SyntaxError: (irb):130: syntax error, unexpected '>'
Car.find_by(:reg_num => 1111, :year<>2014)
                                     ^
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/rmcdonal/Projects/spotlight/bin/rails:9:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /usr/local/rvm/gems/ruby-2.1.8/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.8/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.1.8 :131 >

**Comment by mcdonalduid** [comment]
I tried the following but the generated query does not look correct.
2.1.8 :196 > Car.where(year:2000).where(:reg_num=>2001)
  Car Load (0.2ms)  SELECT cars.* FROM cars WHERE cars.year = ? AND cars.reg_num = ?
 => #<ActiveRecord::Relation [#<Car id: 22, name: "Honda", reg_num: 2001, year: 2000, features: "Coupe", created_at: "2016-07-18 22:49:19", updated_at: "2016-07-18 22:49:19">]>
