### ISSUE TITLE
osx ruby gem ibm_db fails to install on El Capitan 10.11.5

### ISSUE THREAD

**Issue by mramacha** [ibmdb/ruby-ibmdb#61]
Hello,

I am trying to install ibm_db gem on El Capitan 10.11.5 without setting IBM_DB_HOME . I am getting the below error.  

@@@@@@@@@@@
### Building native extensions.  This could take a while...

ERROR:  Error installing ibm_db:
    ERROR: Failed to build gem native extension.

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
```

extconf.rb:93: warning: already initialized constant DOWNLOADLINK
extconf.rb:44: warning: previous definition of DOWNLOADLINK was here
extconf.rb:163: warning: already initialized constant IBM_DB_HOME
extconf.rb:20: warning: previous definition of IBM_DB_HOME was here
extconf.rb:165: warning: already initialized constant IBM_DB_INCLUDE
extconf.rb:150: warning: previous definition of IBM_DB_INCLUDE was here
extconf.rb:166: warning: already initialized constant IBM_DB_LIB
extconf.rb:151: warning: previous definition of IBM_DB_LIB was here
Detected 64-bit Ruby

Detected platform - MacOS darwin64
Environment variable IBM_DB_HOME is not set. Downloading and setting up the DB2 client driver
creating gil_release_version
creating unicode_support_version
checking for SQLConnect() in -ldb2... no
checking for SQLConnect() in -ldb2... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    --with-IBM_DB-dir
    --without-IBM_DB-dir
    --with-IBM_DB-include
    --without-IBM_DB-include=${IBM_DB-dir}/include
    --with-IBM_DB-lib
    --without-IBM_DB-lib=${IBM_DB-dir}/
    --with-db2lib
    --without-db2lib
    --with-db2lib
    --without-db2lib
 extconf failure: Unable to locate libdb2.so/a under /Library/Ruby/Gems/2.0.0/gems/ibm_db-3.0.2/ext/../lib/clidriver/lib

Follow the steps below and retry

Step 1: - Install IBM DB2 Universal Database Server/Client

step 2: - Set the environment variable IBM_DB_HOME as below

```
         (assuming bash shell)

         export IBM_DB_HOME=<DB2/IBM_Data_Server_Driver installation directory> #(Eg: export IBM_DB_HOME=/opt/ibm/db2/v10)
```

step 3: - Retry gem install

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/ibm_db-3.0.2 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/ibm_db-3.0.2/ext/gem_make.out

@@@@@@@@@@@@@@@@@@

my env is as below

rvm_bin_path=/Users/yh00520/.rvm/bin
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/w6/3g2m7jks4p9_bfyvwhjj936jhrdw_h/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.tzVtDwtBFo/Render
TERM_PROGRAM_VERSION=361.1
TERM_SESSION_ID=69EC59AC-E367-4764-A279-D276C2AE49C2
rvm_stored_umask=0022
USER=yh00520
OCI_DIR=/opt/oracle/instantclient_12_1
_system_type=Darwin
DB2HOME=/Users/yh00520/sqllib
rvm_path=/Users/yh00520/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.rn8ErYCy3W/Listeners
__CF_USER_TEXT_ENCODING=0x6186F150:0x0:0x0
rvm_prefix=/Users/yh00520
PATH=/opt/oracle/instantclient_12_1:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/yh00520/.rvm/bin
rvm_loaded_flag=1
PWD=/Users/yh00520
LANG=en_US.UTF-8
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.11
XPC_SERVICE_NAME=0
rvm_version=1.27.0 (latest)
SHLVL=1
HOME=/Users/yh00520
LOGNAME=yh00520
ORACLE_HOME=/opt/oracle/instantclient_12_1
SECURITYSESSIONID=186a7
rvm_user_install_flag=1
_system_name=OSX
_=/usr/bin/env

Appreciate any help. Thanks

**Comment by arvindgu** [comment]
Please ensure that you have permission to gcc and also ensure that you are not missing developer tool.

**Comment by H-pratap** [comment]
@arvindgu : Please provide me the assistance here, i'm facing this error while installing the ibm gem version '2.6.1' on ruby version '2.2.2'. Here is the error:

uilding native extensions.  This could take a while...
ERROR:  Error installing ibm_db:
	ERROR: Failed to build gem native extension.

    /Users/Admin/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20160803-72014-1xoe5m2.rb extconf.rb
Detected 64-bit Ruby
 
Environment variable IBM_DB_HOME is not set. Set it to your DB2/IBM_Data_Server_Driver installation directory and retry gem install.
 

extconf failed, exit code 1

**Comment by arvindgu** [comment]
@H-pratap Can you paste the complete error and also open irb and type RUBY_PLATFORM and enter.
provide the output of it.

**Comment by H-pratap** [comment]
arvind , i've resolved it now, thanks !

**Comment by fran407st** [comment]
Hi friends, nice to meet you. 
I am from Madrid (Spain) and i have a similar problem as H-pratap. I am trying to install gem ibm_db-3.0.4.gem in local with RedHat 7.2 and i obtain this error:

[root@lnxrhel03 ruby-2.3.2]# gem install --local /tmp/ibm_db-3.0.4.gem
Building native extensions.  This could take a while...
ERROR:  Error installing /tmp/ibm_db-3.0.4.gem:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/ibm_db-3.0.4/ext
/usr/local/bin/ruby -r ./siteconf20161126-28684-q5sg4f.rb extconf.rb
extconf.rb:68: warning: already initialized constant DOWNLOADLINK
extconf.rb:44: warning: previous definition of DOWNLOADLINK was here
Detected 64-bit Ruby

Detected platform - linux x86 64
 /opt/ibm/db2/V11.1/include folder not found. Check if you have set the IBM_DB_HOME environment variable's value correctly


extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/ibm_db-3.0.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0-static/ibm_db-3.0.4/gem_make.out


I put you my environment:

[root@lnxrhel03 ruby-2.3.2]# gem -v
2.5.2
[root@lnxrhel03 ruby-2.3.2]# gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.2 (2016-11-15 patchlevel 217) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.3.0
     - /root/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => []
  - REMOTE SOURCES:
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /usr/local/rvm/bin
     - /root/bin
     - /home/db2inst1/sqllib/bin
     - /home/db2inst1/sqllib/adm
     - /home/db2inst1/sqllib/misc

[root@lnxrhel03 ruby-2.3.2]# ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-linux]

I installed the IBM DATA SERVER CLIENT:

[root@lnxrhel03 ruby-2.3.2]# cd /home/db2inst1/
[root@lnxrhel03 db2inst1]# ls -la
total 48
drwxr-xr-x   8 db2inst1 db2iadm1 4096 Nov 25 23:33 .
drwxr-xr-x.  6 root     root     4096 Nov 25 23:09 ..
-rw-------   1 db2inst1 db2iadm1  324 Nov 26 15:51 .bash_history
-rw-r--r--   1 db2inst1 db2iadm1   18 Jul  8  2015 .bash_logout
-rw-r--r--   1 db2inst1 db2iadm1  193 Jul  8  2015 .bash_profile
-rw-r--r--   1 db2inst1 db2iadm1  381 Nov 25 23:09 .bashrc
drwxr-xr-x   3 db2inst1 db2iadm1 4096 Nov 25 23:09 .config
drwxrwxr-x   3 db2inst1 db2iadm1 4096 Nov 25 23:32 .gem
drwxr-xr-x   3 db2inst1 db2iadm1 4096 Nov 25 23:09 .ibm
drwxr-xr-x   3 db2inst1 db2iadm1 4096 Nov 25 23:09 .local
drwxr-xr-x   4 db2inst1 db2iadm1 4096 Nov 25 22:42 .mozilla
drwxrwsr-t  17 db2inst1 db2iadm1 4096 Nov 25 23:09 sqllib

Please i need your help.
Thank you very much.

**Comment by arvindgu** [comment]
You do not need to install IBM Data server client. The ibm_db gem auto downloads the required libraries and configure it. Make sure that you do not set IBM_DB_HOME environment variable. And if it is set to some value, try removing it.
