### ISSUE TITLE
Remote i5/OS (iSeries)

### ISSUE THREAD

**Issue by douglasrlee** [ibmdb/ruby-ibmdb#62]
Is there any documentation or examples of connection to a remote i5/OS (iSeries) database?

**Comment by arvindgu** [comment]
You should be able to connect to a  remote i5/OS (iSeries) database via providing the connection details on database.yml in Rails application.

Or you can create connection as below
conn = IBM_DB.connect('hostname=<servername/IP address>;port=<port>;UID=<user>;PWD=<password>;database=<database name>','','')
