### ISSUE TITLE
decimal values are wrong in ruby representation

### ISSUE THREAD

**Issue by yngad** [ibmdb/ruby-ibmdb#64]
### **Environment**

OS: Linux 3.16.0-50-generic #67~14.04.1-Ubuntu
Ruby: ruby 2.3.1p112 
Rails 4.2.1
ibm_db 3.0.4
Database server        = DB2/LINUXX8664 10.5.5
### **Description**

decimal are beeing stored correctly in the db, but when fetched via active record query e.g. 2.33 will become 2.0. When I change the db adapter to sqlite it works
### **Example**

rails _4.2.1_ new dectest -d ibm_db
rails g model Fee 'amount:decimal{7,2}'
rake db:migrate
### sqlite3

```
f = Fee.new(amount: 1.123)
f.save
f.amount.to_s # => "1.123"
f1 = Fee.find(1) # => <Fee id: 1, amount: #<BigDecimal:7fa41b49eeb0,'0.1123E1',18(27)>....
f1.amount.to_s  # => "1.123"


```
### db2

```
f = Fee.new(amount: 1.123)
f.save
f.amount.to_s # => "1.123"
f1 = Fee.find(1) # => <Fee id: 1, amount: #<BigDecimal:7fa8e9c294c8,'0.1E1',9(18)>....
f1.amount.to_s => "1.0"
```
### notes

describe table Fees # =>AMOUNT SYSIBM DECIMAL 7 2 Yes 
db2 "select amount from fees" # =>  1,12

**Comment by yngad** [comment]
could you reproduce this? Any idea what's going wrong here? 
I can't imagine that this is a general issue since it's such a basic function. But on the other hand my environment is not so fancy...

**Comment by yngad** [comment]
Solved.  My locale was de_DE.UTF-8
changed it to en_US.UTF-8 and now it works. 
But shouldn't it work with de_DE.UTF-8 also?

**Comment by arvindgu** [comment]
You can use [number_with_precision ](https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html)also.
