### ISSUE TITLE
When insert UTF-8 Chinese characters into database, the characters became unreadable

### ISSUE THREAD

**Issue by yoursxin** [ibmdb/ruby-ibmdb#65]
**Environment**
OS:windows 10
Ruby: ruby 2.2
Rails 4.2
ibm_db 3.0.1
Database server = DB2/9.5

**Description**
When I select UTF-8 Chinese characters from database the result is right , but when I insert UTF-8 Chinese characters into database, the characters became unreadable .

**Code**
require 'ibm_db'
conn = IBM_DB.connect('DRIVER={IBM DB2 ODBC=DRIVER};DATABASE=PE;HOSTNAME=xx.xx.xx.xx;PORT=60000;PROTOCOL=TCPIP;UID=xx;PWD=xx;','','')
stmt = IBM_DB.exec(conn,"insert into t_temp (id,desc) values (1,'测试')")
...

Thanks.

**Comment by arvindgu** [comment]
Please confirm whether you able to insert Chinese characters from db2 command.  If not then please check DB2 configuration that you are using correct code page and code set.  Also refer #34.

**Comment by yoursxin** [comment]
Thanks a lot. It works.
created file :  ...\gems\ibm_db-3.0.1-x86-mingw32\lib\clidriver\cfg\db2dsdriver.cfg
content: 

<configuration>
  <parameters>
    <parameter name="DisableUnicode" value="1"/>
  </parameters>
</configuration>
