### ISSUE TITLE
Superclass mismatch for class IBM_DBAdapter (TypeError)

### ISSUE THREAD

**Issue by sithara** [ibmdb/ruby-ibmdb#67]
Hi

I'm using ruby 1.9.3 and rails 3.2.. I came across this error when I tried to exec `bundle exec rspec`

/vendor/bundle/ruby/1.9.1/gems/database_cleaner-0.9.1/lib/database_cleaner/active_record/truncation.rb:196:in `module:ConnectionAdapters': superclass mismatch for class IBM_DBAdapter (TypeError)

**Comment by arvindgu** [comment]
Support for Ruby 1.9.3 has already ended.
https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

Rails 3.2 is also not supported anymore.
http://guides.rubyonrails.org/maintenance_policy.html

We do not support the ibm_db gem on unsupported versions of Ruby and Rails. 
Hence it is recommended to keep upgrading the Ruby and Rails both.
