### ISSUE TITLE
Should ibm_db adapter work with Rails 5?

### ISSUE THREAD

**Issue by dwadler** [ibmdb/ruby-ibmdb#69]
I created a new application with:
rails new db2test --database=ibm_db
and put the connection parameters in db2test\config\database.yml
I then executed
rails generate scaffold Book title:string description:string
but it failed with:
rails db:migrate
it failed with:

E:\dwacode\rails5\db2test>rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rails aborted!
ArgumentError: wrong number of arguments (given 5, expected 3..4)
d:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-3.0.4-x86-mingw32/lib/active_record/co
nnection_adapters/ibm_db_adapter.rb:283:in `create_table_definition'
d:/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connec
tion_adapters/abstract/schema_statements.rb:263:in `create_table'
d:/Ruby23/lib/ruby/gems/2.3.0/gems/ibm_db-3.0.4-x86-mingw32/lib/active_record/co
nnection_adapters/ibm_db_adapter.rb:874:in `create_table'
d:/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/schema
_migration.rb:27:in `create_table'
d:/Ruby23/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connec
tion_adapters/abstract/schema_statements.rb:1010:in `initialize_schema_migration
s_table'

**Comment by yngad** [comment]
I have the same issue. Can anyone answer this question?

**Comment by holgum** [comment]
@arvindgu  Are there any plans to update this for Rails 5?

**Comment by arvindgu** [comment]
@holgum yes we do have a plan to update the ibm_gb gem to Rails 5 in long term. We are also open to accept the contribution from others.

**Comment by AndreaRibuoli** [comment]
Could you be more specific with "long term"? Thanks.

**Comment by dwadler** [comment]
Any progress on this?

**Comment by AndreaRibuoli** [comment]
Hi David,

  we (PowerRuby Ltd) developed specialized(and private) Ruby driver and Rails adapter for IBM i DB2.
This adapter supports Rails 5.1 but was a complete departure from the original attempt of PowerRuby Community Edition to adapt ruby_ibmdb for IBM i DB2. 
Our development was meant to leverage specialized features of IBM i DB2 (.e.g. the support for field level CCSID setting).

If you are targeting any of the LUW DB2 platforms our development would not help you anyway.

I have never received any reply from IBM India concerning their plans.

Regards,

    Andrea

**Comment by arvindgu** [comment]
We have recently released Rails 5 Toleration support (without adding any new features of Rails 5).
Please test and let us know your feedback.

**Comment by yngad** [comment]
we switched to postgres meanwhile...
