### ISSUE TITLE
Emails to opendev@us.ibm.com bounce.

### ISSUE THREAD

**Issue by rebel** [ibmdb/ruby-ibmdb#72]
Hello,

I tried to email opendev@us.ibm.com which is listed here in this github project as a contact point and received a bounce message:

Generating server: d03hub03.boulder.ibm.com

opendev@us.ibm.com
#< #5.1.1 X-Notes; User opendev (opendev@us.ibm.com) not listed in Domino Directory> #SMTP#

**Comment by arvindgu** [comment]
Hi,

The opendev@us.ibm.com is not valid anymore. 

To report an issue, open an issue [here](https://github.com/ibmdb/ruby-ibmdb/issues/) in Github.

Regards,
