### ISSUE TITLE
ibm_db gem not supporting DB version 11 - Only DB2 z/OS version 8 and above are currently supported

### ISSUE THREAD

**Issue by vignesh9136** [ibmdb/ruby-ibmdb#73]
Hi,

Currently ibm_db ruby gem supports only the DB_version till 10 and for DB version of 11 it throws error as "Only DB2 z/OS version 8 and above are currently supported"

issue file:
https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L658

**Comment by lucasvel** [comment]
I just stumble upon this issue. 

A quick fix that worked for me **locally** is either adding the 2 following lines in the case block ([here](https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L650))
```
when /11/
  @servertype = IBM_DB2_ZOS.new(self, @isAr3)
```

or changing the `when`matcher [here](https://github.com/ibmdb/ruby-ibmdb/blob/master/IBM_DB_Adapter/ibm_db/lib/active_record/connection_adapters/ibm_db_adapter.rb#L653) to be
```
when /10|11/
  @servertype = IBM_DB2_ZOS.new(self, @isAr3)
```

**Comment by arvindgu** [comment]
Yes, the code change required to support all the versions of DB2.

**Comment by matthewkrom** [comment]
This appears not to be added to v4.0.0 of this gem. Also, it appears there may now be a v12 to match against.

**Comment by akhilravuri1** [comment]
Please feel free to reopen the issue if you are facing this with the latest driver.

**Comment by matthewkrom** [comment]
This appears to still be an issue. See Feb 24 comment: Not only does it throw an error against v11, it also throws an error against v12. The latest source code for ibm_db_adapter.rb at line 800 clearly does not handle v11 or 12 (only 08, 09, and 10).  This has been an open issue for 3 years now. Is this library seriously maintained?
