### ISSUE TITLE
Ruby 2.4+ compatibility 

### ISSUE THREAD

**Issue by Montti37** [ibmdb/ruby-ibmdb#76]
Any plans to update to work with newer versions of ruby?

**Comment by jflohre** [comment]
Any updates that?  or does anyone have a workaround?

**Comment by Montti37** [comment]
I just switched to jruby and used a jdbc

**Comment by jflohre** [comment]
@Montti37 any way you can descrive wha tall you did to get it to work?  Did you use Active Record along with the jruby + jdbc and stop using the gem?

**Comment by Montti37** [comment]
@jflohre I am using Jruby along with the gem sequel to connect, i am no longer using IBM_DB   
this is my connection method

`require './java/db2jcc.jar'
class DB2
  def self.execute_sql
    Sequel.connect(adapter: "jdbc",
                   url: jdbc:db2://my_database_address,
                   user: $context.authentication["db2_database"]["username"],
                   password: Crypt.decrypt($context.authentication["db2_database"]["password"]))
  end
end`

**Comment by jflohre** [comment]
@Montti37  Thanks for the quick reply!

**Comment by arvindgu** [comment]
Currently we do not support Ruby 2.4+.  We will plan to have to in near future. We have noted this and closing this issue for now.
