### ISSUE TITLE
Segmentation fault crash on Ruby 2.4.4

### ISSUE THREAD

**Issue by leonsp** [ibmdb/ruby-ibmdb#77]
I'm not sure if this is an `ibm_db` or a Ruby issue, but I'm seeing a lot of crashes from a Rails 4.2.10 + Ruby 2.4.4 + ibm_db 3.0.5 app. From #76 I understand that ibm_db does not yet support Ruby 2.4.x. Here's a stack dump: https://gist.github.com/leonsp/6be58208d76c95b508858d9e0ea1d57c

**Comment by akhilravuri1** [comment]
Hi @leonsp 
we have released a new version in the ibm_db driver which supports till 2.6.5 and rails v6.
Please update the driver.
Thanks,
Akhil
