### ISSUE TITLE
cannot load such file -- arel/visitors/bind_visitor

### ISSUE THREAD

**Issue by seanhogge** [ibmdb/ruby-ibmdb#78]
I'm using Rails 5.2.0 on Ruby 2.3.4 to connect to MySQL (via `mysql2` gem)and DB2 (via `ibm_db` gem) databases.

When I attempt to connect to the DB2, I get:

`Error loading the 'ibm_db' Active Record adapter. Missing a gem it depends on? cannot load such file -- arel/visitors/bind_visitor`

and the trace calls out

`ibm_db (4.0.0) lib/active_record/connection_adapters/ibm_db_adapter.rb:13:in <main>'`

which consists of

`require 'arel/visitors/bind_visitor'`

It certainly looks like it's trying to load a dependency, but it's not able to. `bundle install` returns no errors.

I'm not sure how to check that the Bind_Visitors module is installed correctly, or what else might cause this error. Please let me know if you need to see any logs or the Gemfile.

**Comment by jeremiahlukus** [comment]
@seanhogge  Hey, how did you fix this?

**Comment by SymphonicJohn** [comment]
@seanhogge How did you resolve? Thanks

**Comment by SymphonicJohn** [comment]
It looks like the odbc gem is outdated and predates arel getting absorbed into active record. I fixed it by commenting out the call to include arel from odbc within vendor/bundle... but I am still working out other kinks. Thanks for the quick response.

**Comment by seanhogge** [comment]
Interesting. If you do end up getting it working, please let me know here. I'd be interested to try it again if there's a path forward.

**Comment by calh** [comment]
Can this issue be reopened?  I'm running into this error when running tests with ibm_db 4.0.0 and activesupport 5.2.3:
```
Caused by:
LoadError: cannot load such file -- arel/visitors/bind_visitor
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/.bundle/ruby/2.5.0/gems/ibm_db-4.0.0/lib/active_record/connection_adapters/ibm_db_adapter.rb:13:in `<top (required)>'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/lib/octopus/proxy_config.rb:245:in `initialize_adapter'
```
