### ISSUE TITLE
gem not working after upgrade to MacOS Mojave

### ISSUE THREAD

**Issue by vhtellez** [ibmdb/ruby-ibmdb#80]
This message will come up everytime a connection is initialized

```
objc[15052]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[15052]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

It seems to be related to Ruby version, this happens using the recommended version Ruby : 2.2.6

Which versions of rails and ruby will recommend?

**Comment by regismesquita** [comment]
There is a suggested solution referenced here:
https://github.com/darkskyapp/forecast-ruby/issues/13#issuecomment-432464692

> export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

**Comment by Wallaceh** [comment]
This is actually an issue related to the OS update. This is an article that explains why its happening:

https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/

Run this in terminal to fix it:

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
