### ISSUE TITLE
Convert to using `limit` functionality

### ISSUE THREAD

**Issue by mhqops** [ibmdb/ruby-ibmdb#81]
I'm using DB2WoC.  I'm using the ActiveRecord with `ibm_db` gem.  The following query only returns 1 row:

```
User.limit(20)
```

The SQL generated by that command is:

```
SELECT O.* FROM (
  SELECT 
    I.*, 
    ROW_NUMBER() OVER () sys_row_num 
  FROM (  
    SELECT 
      ibm_staging.users.* 
     FROM ibm_staging.users  
  ) AS I
) AS O 
WHERE sys_row_num BETWEEN 0 AND 1
```

**Comment by sma3** [comment]
Just updated from rails 4.2.1 to 5.0.7 and have exactly the same problem. Could you figure it out meanwhile?

**Comment by sma3** [comment]
in _ibm_db_adapter.rb_ I changed the line
`if(offset.nil? && limit.nil?) `
to
i`f(offset.to_i == 0 && limit.to_i == 0)`  
and that works for me. (I didn't test a lo so long)
We have V10.5 installed on Ubuntu

**Comment by akhilravuri1** [comment]
Please feel free to reopen the issue if you are facing this with the latest driver.
