### ISSUE TITLE
Only able to use ibm_db with ruby 2.2 which is EOL

### ISSUE THREAD

**Issue by phurley** [ibmdb/ruby-ibmdb#85]
Any timeline on an update? I have a DB2 customer who I would rather not ask to switch to a different database; however, you are making it difficult to recommend staying with DB2.

**Comment by phurley** [comment]
FYI: https://www.ruby-lang.org/en/downloads/branches/

**Comment by dapper-hacker** [comment]
@phurley Ruby 2.5.6 and Rails v6 support has been released now.

**Comment by akhilravuri1** [comment]
Thanks @dapper-hacker  for the update.

@phurley ibm_db 5.0.2 version is released which supports till ruby 2.6.5 and rails v6.

I will close this as we support the latest ruby and rails versions.
Please update the driver and if you face issues please feel free to open a new issue.

Thanks,
Akhil
