### ISSUE TITLE
Ruby on Rails Support 

### ISSUE THREAD

**Issue by dapper-hacker** [ibmdb/ruby-ibmdb#92]
What is the status of Ruby on Rails support?  
The last release of the ibm_db gem (4.0.0, August 2018) didn’t even support Rails 5.2 (it was released in April, 2018). 
Rails 6 is coming soon, too.
What is the plan to support Ruby on Rails ?

**Comment by matthewkrom** [comment]
It's been 9 months, and I don't see any update here.  ibm_db 4.0.0 is still the latest ruby gem, and it still doesn't support Rails 5.2.

**Comment by matthewkrom** [comment]
The error is:  

from .../gems/activesupport-5.2.4.2/lib/active_support/dependencies:291:in `require`

Error loading the 'ibm_db' Active Record adapter. Missing a gem it depends on? cannot load such file -- arel/visitors/bind_visitor (LoadError)

**Comment by idbjorh** [comment]
It has been announced publicly (see https://youtu.be/hvwUKUVzEAE?t=1542) that IBM will be releasing an updated version of the ibm_db gem, and will also have support for Rails 6.  

Hopefully this also means that this repo will start seeing some care and feeding on a regular basis.

**Comment by akhilravuri1** [comment]
Yes @idbjorh 
we will be releasing the new version of the ruby driver on May 6th or 7th.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
@matthewkrom 
sorry for the late but update but we will be releasing the new version as early as possible and thanks for showing interest in our ruby_ibm_driver.

-Akhil

**Comment by matthewkrom** [comment]
@idbjorh and @akhilravuri1 Thanks for the information! When you say May 6 or 7, do you mean May 16 or 17? (It's May 10 US time right now.)

**Comment by akhilravuri1** [comment]
@matthewkrom May 11 (Monday) or 12 (Tuesday)

**Comment by matthewkrom** [comment]
I see ibm_db gem 5.0.1 and 5.0.2 are on rubygems.org right now — fantastic! I'll wait a day or two to see if any other updates coming, then will try with Rails 5.2.4.2 (latest 5.2)

**Comment by akhilravuri1** [comment]
Hi @matthewkrom 

Please install ruby ibm_db gem 5.0.2 and give a try.

If face any issues, please feel free to open a new issue.

I will close this issue for now.

Thanks,
Akhil
