### ISSUE TITLE
IBM_DB 4.0.0 unable to load module

### ISSUE THREAD

**Issue by aswerlein511** [ibmdb/ruby-ibmdb#94]
I am currently trying to upgrade my Ruby from 2.3.3 where I have had no issues using the Sequel gem and the IBM_DB gem as the adapter.  I am trying to upgrade to Ruby 2.5.5 or Ruby 2.6.4 and I am getting this same error.

LoadError (126: The specified module could not be found.   - C:/Ruby26/lib/ruby/gems/2.6.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so)

I am unable to find any resolution to this problem, but I do know that file does exist in the specified path.  Do you have any ideas as to why this is happening when upgrading Ruby language?

**Comment by aswerlein511** [comment]
Location of fialure in the code base. 
C:\Ruby26\lib\ruby\gems\2.6.0\gems\ibm_db-4.0.0-x86-mingw32\lib\mswin32\ibm_db.rb: 90 
             require 'rb2x/i386/ibm_db.so'
I added this check and it returns true:

p "******** FIle exists: #{File.exists?('C:\Ruby26\lib\ruby\gems\2.6.0\gems\ibm_db-4.0.0-x86-mingw32\lib\mswin32\rb2x\i386\ibm_db.so')}"

"******** FIle exists: true"

**Comment by akhilravuri1** [comment]
Hi @aswerlein511 

I assume you are installing the ibm_db gem on windows so please set this env variable.
```
set RUBY_DLL_PATH=/path/to/clidriver/bin
example:-
set RUBY_DLL_PATH=C:\Users\rakhil\go_ibm_db\clidriver\bin
```

Thanks,
Akhil

**Comment by aswerlein511** [comment]
I uninstalled all versions of ibm_db from my machine.  Set the path as follows:

RUBY_DLL_PATH=C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0-x86-mingw32/lib/clidriver/bin

I installed the latest version of the gem.  

Opened irb

require 'ibm_db'

and this is the output: 

LoadError (126: The specified module could not be found.   - C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so)

This is the same error as before.

**Comment by akhilravuri1** [comment]
Hi @aswerlein511 

no need to require 'mswin32/ibm_db'

just use require 'ibm_db'



> LoadError (126: The specified module could not be found. - C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x/i386/ibm_db.so)

Again if you are getting this issue after setting the above env please do follow this steps

1) go to this (C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0-x86-mingw32/lib/mswin32/rb2x) directory  and check for i386/ibm_db.so file.
2) If the above file is present please give me the output of ls in this (C:/Ruby25/lib/ruby/gems/2.5.0/gems/ibm_db-4.0.0-x86-mingw32/lib/clidriver/bin) directory.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @aswerlein511 

we have released a new version for ruby ibm_db.
please update the driver.

closing the issue...if you face any issues, please feel free to open new issues.

Thanks,
Akhil
