### ISSUE TITLE
Migrate Arel code from Rails to ibmdb adapter

### ISSUE THREAD

**Issue by simi** [ibmdb/ruby-ibmdb#98]
:information_source: ibmdb arel visitor would be removed from rails - rails/rails#38946 and it would need to be vendored.

You can inspire at oracle-enhanced repo doing the same https://github.com/rsim/oracle-enhanced/pull/2002.

**Comment by akhilravuri1** [comment]
Hi @simi 
sorry for the late reply.



> ibmdb arel visitor would be removed from rails

removed means the arel-7.1.4\lib\arel\visitors\ibm_db.rb file will be removed?

Thanks,
Akhil
